/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ProveapiError } from "./proveapierror.js";

export type Error403Data = {
  /**
   * The input ClientRequestID, echoed when provided on the request.
   */
  clientRequestId?: string | undefined;
  /**
   * An error code that identifies the specific authorization issue.
   */
  code?: number | undefined;
  /**
   * The correlation ID for the flow, echoed when available.
   */
  correlationId?: string | undefined;
  /**
   * The error message describing why access is forbidden.
   */
  message: string;
};

export class Error403 extends ProveapiError {
  /**
   * The input ClientRequestID, echoed when provided on the request.
   */
  clientRequestId?: string | undefined;
  /**
   * An error code that identifies the specific authorization issue.
   */
  code?: number | undefined;
  /**
   * The correlation ID for the flow, echoed when available.
   */
  correlationId?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: Error403Data;

  constructor(
    err: Error403Data,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.clientRequestId != null) this.clientRequestId = err.clientRequestId;
    if (err.code != null) this.code = err.code;
    if (err.correlationId != null) this.correlationId = err.correlationId;

    this.name = "Error403";
  }
}

/** @internal */
export const Error403$inboundSchema: z.ZodType<
  Error403,
  z.ZodTypeDef,
  unknown
> = z.object({
  clientRequestId: z.string().optional(),
  code: z.number().int().optional(),
  correlationId: z.string().optional(),
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new Error403(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type Error403$Outbound = {
  clientRequestId?: string | undefined;
  code?: number | undefined;
  correlationId?: string | undefined;
  message: string;
};

/** @internal */
export const Error403$outboundSchema: z.ZodType<
  Error403$Outbound,
  z.ZodTypeDef,
  Error403
> = z.instanceof(Error403)
  .transform(v => v.data$)
  .pipe(z.object({
    clientRequestId: z.string().optional(),
    code: z.number().int().optional(),
    correlationId: z.string().optional(),
    message: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Error403$ {
  /** @deprecated use `Error403$inboundSchema` instead. */
  export const inboundSchema = Error403$inboundSchema;
  /** @deprecated use `Error403$outboundSchema` instead. */
  export const outboundSchema = Error403$outboundSchema;
  /** @deprecated use `Error403$Outbound` instead. */
  export type Outbound = Error403$Outbound;
}
