/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { authAuthContinueRequest } from "../funcs/authAuthContinueRequest.js";
import { authAuthFinishRequest } from "../funcs/authAuthFinishRequest.js";
import { authAuthStartRequest } from "../funcs/authAuthStartRequest.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Auth extends ClientSDK {
  /**
   * AuthContinue /v1/server/auth/continue
   *
   * @remarks
   * If the initial Prove Auth authenticators fail, the Force Bind authenticator can be used which permits using another
   * authentication method to verify a mobile number (like Prove Instant Link™). Once the mobile number is verified, send
   * this AuthContinue request.
   *
   * Production URL: https://oapi.prove-auth.proveapis.com/v1/server/auth/continue
   */
  async authContinueRequest(
    request?: components.AuthContinueRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.AuthContinueRequestResponse> {
    return unwrapAsync(authAuthContinueRequest(
      this,
      request,
      options,
    ));
  }

  /**
   * AuthFinish /v1/server/auth/finish
   *
   * @remarks
   * To complete the auth flow and get the authentication result, send this AuthFinish request.
   *
   * Production URL: https://oapi.prove-auth.proveapis.com/v1/server/auth/finish
   */
  async authFinishRequest(
    request?: components.AuthFinishRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.AuthFinishRequestResponse> {
    return unwrapAsync(authAuthFinishRequest(
      this,
      request,
      options,
    ));
  }

  /**
   * AuthStart /v1/server/auth/start
   *
   * @remarks
   * To start an auth flow, send this AuthStart request to control how Prove Auth will authenticate the end users and
   * their devices. The expected authenticators should be included in the body parameters. There are many supported
   * scenarios to use Prove Auth so each of the request types are explained in the "Server Integration Guide".
   *
   * Production URL: https://oapi.prove-auth.proveapis.com/v1/server/auth/start
   */
  async authStartRequest(
    request?: components.AuthStartRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.AuthStartRequestResponse> {
    return unwrapAsync(authAuthStartRequest(
      this,
      request,
      options,
    ));
  }
}
