/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V3BatchEnrollIdentitiesResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * V3BatchEnrollIdentitiesResponse
   */
  v3BatchEnrollIdentitiesResponse?:
    | components.V3BatchEnrollIdentitiesResponse
    | undefined;
};

/** @internal */
export const V3BatchEnrollIdentitiesResponse$inboundSchema: z.ZodType<
  V3BatchEnrollIdentitiesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  V3BatchEnrollIdentitiesResponse: components
    .V3BatchEnrollIdentitiesResponse$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "V3BatchEnrollIdentitiesResponse": "v3BatchEnrollIdentitiesResponse",
  });
});

/** @internal */
export type V3BatchEnrollIdentitiesResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  V3BatchEnrollIdentitiesResponse?:
    | components.V3BatchEnrollIdentitiesResponse$Outbound
    | undefined;
};

/** @internal */
export const V3BatchEnrollIdentitiesResponse$outboundSchema: z.ZodType<
  V3BatchEnrollIdentitiesResponse$Outbound,
  z.ZodTypeDef,
  V3BatchEnrollIdentitiesResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  v3BatchEnrollIdentitiesResponse: components
    .V3BatchEnrollIdentitiesResponse$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    v3BatchEnrollIdentitiesResponse: "V3BatchEnrollIdentitiesResponse",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3BatchEnrollIdentitiesResponse$ {
  /** @deprecated use `V3BatchEnrollIdentitiesResponse$inboundSchema` instead. */
  export const inboundSchema = V3BatchEnrollIdentitiesResponse$inboundSchema;
  /** @deprecated use `V3BatchEnrollIdentitiesResponse$outboundSchema` instead. */
  export const outboundSchema = V3BatchEnrollIdentitiesResponse$outboundSchema;
  /** @deprecated use `V3BatchEnrollIdentitiesResponse$Outbound` instead. */
  export type Outbound = V3BatchEnrollIdentitiesResponse$Outbound;
}

export function v3BatchEnrollIdentitiesResponseToJSON(
  v3BatchEnrollIdentitiesResponse: V3BatchEnrollIdentitiesResponse,
): string {
  return JSON.stringify(
    V3BatchEnrollIdentitiesResponse$outboundSchema.parse(
      v3BatchEnrollIdentitiesResponse,
    ),
  );
}

export function v3BatchEnrollIdentitiesResponseFromJSON(
  jsonString: string,
): SafeParseResult<V3BatchEnrollIdentitiesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3BatchEnrollIdentitiesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3BatchEnrollIdentitiesResponse' from JSON`,
  );
}
