/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V3CompleteRequestResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Successful request.
   */
  v3CompleteResponse?: components.V3CompleteResponse | undefined;
};

/** @internal */
export const V3CompleteRequestResponse$inboundSchema: z.ZodType<
  V3CompleteRequestResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  V3CompleteResponse: components.V3CompleteResponse$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "V3CompleteResponse": "v3CompleteResponse",
  });
});

/** @internal */
export type V3CompleteRequestResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  V3CompleteResponse?: components.V3CompleteResponse$Outbound | undefined;
};

/** @internal */
export const V3CompleteRequestResponse$outboundSchema: z.ZodType<
  V3CompleteRequestResponse$Outbound,
  z.ZodTypeDef,
  V3CompleteRequestResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  v3CompleteResponse: components.V3CompleteResponse$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    v3CompleteResponse: "V3CompleteResponse",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3CompleteRequestResponse$ {
  /** @deprecated use `V3CompleteRequestResponse$inboundSchema` instead. */
  export const inboundSchema = V3CompleteRequestResponse$inboundSchema;
  /** @deprecated use `V3CompleteRequestResponse$outboundSchema` instead. */
  export const outboundSchema = V3CompleteRequestResponse$outboundSchema;
  /** @deprecated use `V3CompleteRequestResponse$Outbound` instead. */
  export type Outbound = V3CompleteRequestResponse$Outbound;
}

export function v3CompleteRequestResponseToJSON(
  v3CompleteRequestResponse: V3CompleteRequestResponse,
): string {
  return JSON.stringify(
    V3CompleteRequestResponse$outboundSchema.parse(v3CompleteRequestResponse),
  );
}

export function v3CompleteRequestResponseFromJSON(
  jsonString: string,
): SafeParseResult<V3CompleteRequestResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3CompleteRequestResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3CompleteRequestResponse' from JSON`,
  );
}
