/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V3DomainIDResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * V3DomainIDResponse
   */
  v3DomainIDResponse?: components.V3DomainIDResponse | undefined;
};

/** @internal */
export const V3DomainIDResponse$inboundSchema: z.ZodType<
  V3DomainIDResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  V3DomainIDResponse: components.V3DomainIDResponse$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "V3DomainIDResponse": "v3DomainIDResponse",
  });
});

/** @internal */
export type V3DomainIDResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  V3DomainIDResponse?: components.V3DomainIDResponse$Outbound | undefined;
};

/** @internal */
export const V3DomainIDResponse$outboundSchema: z.ZodType<
  V3DomainIDResponse$Outbound,
  z.ZodTypeDef,
  V3DomainIDResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  v3DomainIDResponse: components.V3DomainIDResponse$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    v3DomainIDResponse: "V3DomainIDResponse",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3DomainIDResponse$ {
  /** @deprecated use `V3DomainIDResponse$inboundSchema` instead. */
  export const inboundSchema = V3DomainIDResponse$inboundSchema;
  /** @deprecated use `V3DomainIDResponse$outboundSchema` instead. */
  export const outboundSchema = V3DomainIDResponse$outboundSchema;
  /** @deprecated use `V3DomainIDResponse$Outbound` instead. */
  export type Outbound = V3DomainIDResponse$Outbound;
}

export function v3DomainIDResponseToJSON(
  v3DomainIDResponse: V3DomainIDResponse,
): string {
  return JSON.stringify(
    V3DomainIDResponse$outboundSchema.parse(v3DomainIDResponse),
  );
}

export function v3DomainIDResponseFromJSON(
  jsonString: string,
): SafeParseResult<V3DomainIDResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3DomainIDResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3DomainIDResponse' from JSON`,
  );
}
