/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V3DomainUnlinkResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * V3DomainUnlinkResponse
   */
  v3DomainUnlinkResponse?: components.V3DomainUnlinkResponse | undefined;
};

/** @internal */
export const V3DomainUnlinkResponse$inboundSchema: z.ZodType<
  V3DomainUnlinkResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  V3DomainUnlinkResponse: components.V3DomainUnlinkResponse$inboundSchema
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "V3DomainUnlinkResponse": "v3DomainUnlinkResponse",
  });
});

/** @internal */
export type V3DomainUnlinkResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  V3DomainUnlinkResponse?:
    | components.V3DomainUnlinkResponse$Outbound
    | undefined;
};

/** @internal */
export const V3DomainUnlinkResponse$outboundSchema: z.ZodType<
  V3DomainUnlinkResponse$Outbound,
  z.ZodTypeDef,
  V3DomainUnlinkResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  v3DomainUnlinkResponse: components.V3DomainUnlinkResponse$outboundSchema
    .optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    v3DomainUnlinkResponse: "V3DomainUnlinkResponse",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3DomainUnlinkResponse$ {
  /** @deprecated use `V3DomainUnlinkResponse$inboundSchema` instead. */
  export const inboundSchema = V3DomainUnlinkResponse$inboundSchema;
  /** @deprecated use `V3DomainUnlinkResponse$outboundSchema` instead. */
  export const outboundSchema = V3DomainUnlinkResponse$outboundSchema;
  /** @deprecated use `V3DomainUnlinkResponse$Outbound` instead. */
  export type Outbound = V3DomainUnlinkResponse$Outbound;
}

export function v3DomainUnlinkResponseToJSON(
  v3DomainUnlinkResponse: V3DomainUnlinkResponse,
): string {
  return JSON.stringify(
    V3DomainUnlinkResponse$outboundSchema.parse(v3DomainUnlinkResponse),
  );
}

export function v3DomainUnlinkResponseFromJSON(
  jsonString: string,
): SafeParseResult<V3DomainUnlinkResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3DomainUnlinkResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3DomainUnlinkResponse' from JSON`,
  );
}
