/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V3DomainLinkedRequestResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Successful request.
   */
  v3DomainLinkedResponse?: components.V3DomainLinkedResponse | undefined;
  headers: { [k: string]: Array<string> };
};

/** @internal */
export const V3DomainLinkedRequestResponse$inboundSchema: z.ZodType<
  V3DomainLinkedRequestResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  V3DomainLinkedResponse: components.V3DomainLinkedResponse$inboundSchema
    .optional(),
  Headers: z.record(z.array(z.string())),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "V3DomainLinkedResponse": "v3DomainLinkedResponse",
    "Headers": "headers",
  });
});

/** @internal */
export type V3DomainLinkedRequestResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  V3DomainLinkedResponse?:
    | components.V3DomainLinkedResponse$Outbound
    | undefined;
  Headers: { [k: string]: Array<string> };
};

/** @internal */
export const V3DomainLinkedRequestResponse$outboundSchema: z.ZodType<
  V3DomainLinkedRequestResponse$Outbound,
  z.ZodTypeDef,
  V3DomainLinkedRequestResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  v3DomainLinkedResponse: components.V3DomainLinkedResponse$outboundSchema
    .optional(),
  headers: z.record(z.array(z.string())),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    v3DomainLinkedResponse: "V3DomainLinkedResponse",
    headers: "Headers",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3DomainLinkedRequestResponse$ {
  /** @deprecated use `V3DomainLinkedRequestResponse$inboundSchema` instead. */
  export const inboundSchema = V3DomainLinkedRequestResponse$inboundSchema;
  /** @deprecated use `V3DomainLinkedRequestResponse$outboundSchema` instead. */
  export const outboundSchema = V3DomainLinkedRequestResponse$outboundSchema;
  /** @deprecated use `V3DomainLinkedRequestResponse$Outbound` instead. */
  export type Outbound = V3DomainLinkedRequestResponse$Outbound;
}

export function v3DomainLinkedRequestResponseToJSON(
  v3DomainLinkedRequestResponse: V3DomainLinkedRequestResponse,
): string {
  return JSON.stringify(
    V3DomainLinkedRequestResponse$outboundSchema.parse(
      v3DomainLinkedRequestResponse,
    ),
  );
}

export function v3DomainLinkedRequestResponseFromJSON(
  jsonString: string,
): SafeParseResult<V3DomainLinkedRequestResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3DomainLinkedRequestResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3DomainLinkedRequestResponse' from JSON`,
  );
}
