/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V3DomainConfirmLinkRequestResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * V3DomainConfirmLinkResponse
   */
  v3DomainConfirmLinkResponse?:
    | components.V3DomainConfirmLinkResponse
    | undefined;
};

/** @internal */
export const V3DomainConfirmLinkRequestResponse$inboundSchema: z.ZodType<
  V3DomainConfirmLinkRequestResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  V3DomainConfirmLinkResponse: components
    .V3DomainConfirmLinkResponse$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "V3DomainConfirmLinkResponse": "v3DomainConfirmLinkResponse",
  });
});

/** @internal */
export type V3DomainConfirmLinkRequestResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  V3DomainConfirmLinkResponse?:
    | components.V3DomainConfirmLinkResponse$Outbound
    | undefined;
};

/** @internal */
export const V3DomainConfirmLinkRequestResponse$outboundSchema: z.ZodType<
  V3DomainConfirmLinkRequestResponse$Outbound,
  z.ZodTypeDef,
  V3DomainConfirmLinkRequestResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  v3DomainConfirmLinkResponse: components
    .V3DomainConfirmLinkResponse$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    v3DomainConfirmLinkResponse: "V3DomainConfirmLinkResponse",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3DomainConfirmLinkRequestResponse$ {
  /** @deprecated use `V3DomainConfirmLinkRequestResponse$inboundSchema` instead. */
  export const inboundSchema = V3DomainConfirmLinkRequestResponse$inboundSchema;
  /** @deprecated use `V3DomainConfirmLinkRequestResponse$outboundSchema` instead. */
  export const outboundSchema =
    V3DomainConfirmLinkRequestResponse$outboundSchema;
  /** @deprecated use `V3DomainConfirmLinkRequestResponse$Outbound` instead. */
  export type Outbound = V3DomainConfirmLinkRequestResponse$Outbound;
}

export function v3DomainConfirmLinkRequestResponseToJSON(
  v3DomainConfirmLinkRequestResponse: V3DomainConfirmLinkRequestResponse,
): string {
  return JSON.stringify(
    V3DomainConfirmLinkRequestResponse$outboundSchema.parse(
      v3DomainConfirmLinkRequestResponse,
    ),
  );
}

export function v3DomainConfirmLinkRequestResponseFromJSON(
  jsonString: string,
): SafeParseResult<V3DomainConfirmLinkRequestResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      V3DomainConfirmLinkRequestResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3DomainConfirmLinkRequestResponse' from JSON`,
  );
}
