/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V3StartRequestResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Successful request.
   */
  v3StartResponse?: components.V3StartResponse | undefined;
};

/** @internal */
export const V3StartRequestResponse$inboundSchema: z.ZodType<
  V3StartRequestResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  V3StartResponse: components.V3StartResponse$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "V3StartResponse": "v3StartResponse",
  });
});

/** @internal */
export type V3StartRequestResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  V3StartResponse?: components.V3StartResponse$Outbound | undefined;
};

/** @internal */
export const V3StartRequestResponse$outboundSchema: z.ZodType<
  V3StartRequestResponse$Outbound,
  z.ZodTypeDef,
  V3StartRequestResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  v3StartResponse: components.V3StartResponse$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    v3StartResponse: "V3StartResponse",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3StartRequestResponse$ {
  /** @deprecated use `V3StartRequestResponse$inboundSchema` instead. */
  export const inboundSchema = V3StartRequestResponse$inboundSchema;
  /** @deprecated use `V3StartRequestResponse$outboundSchema` instead. */
  export const outboundSchema = V3StartRequestResponse$outboundSchema;
  /** @deprecated use `V3StartRequestResponse$Outbound` instead. */
  export type Outbound = V3StartRequestResponse$Outbound;
}

export function v3StartRequestResponseToJSON(
  v3StartRequestResponse: V3StartRequestResponse,
): string {
  return JSON.stringify(
    V3StartRequestResponse$outboundSchema.parse(v3StartRequestResponse),
  );
}

export function v3StartRequestResponseFromJSON(
  jsonString: string,
): SafeParseResult<V3StartRequestResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3StartRequestResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3StartRequestResponse' from JSON`,
  );
}
