/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V3UnifyStatusRequestResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Successful Request
   */
  v3UnifyStatusResponse?: components.V3UnifyStatusResponse | undefined;
  headers: { [k: string]: Array<string> };
};

/** @internal */
export const V3UnifyStatusRequestResponse$inboundSchema: z.ZodType<
  V3UnifyStatusRequestResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  V3UnifyStatusResponse: components.V3UnifyStatusResponse$inboundSchema
    .optional(),
  Headers: z.record(z.array(z.string())),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "V3UnifyStatusResponse": "v3UnifyStatusResponse",
    "Headers": "headers",
  });
});

/** @internal */
export type V3UnifyStatusRequestResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  V3UnifyStatusResponse?: components.V3UnifyStatusResponse$Outbound | undefined;
  Headers: { [k: string]: Array<string> };
};

/** @internal */
export const V3UnifyStatusRequestResponse$outboundSchema: z.ZodType<
  V3UnifyStatusRequestResponse$Outbound,
  z.ZodTypeDef,
  V3UnifyStatusRequestResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  v3UnifyStatusResponse: components.V3UnifyStatusResponse$outboundSchema
    .optional(),
  headers: z.record(z.array(z.string())),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    v3UnifyStatusResponse: "V3UnifyStatusResponse",
    headers: "Headers",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3UnifyStatusRequestResponse$ {
  /** @deprecated use `V3UnifyStatusRequestResponse$inboundSchema` instead. */
  export const inboundSchema = V3UnifyStatusRequestResponse$inboundSchema;
  /** @deprecated use `V3UnifyStatusRequestResponse$outboundSchema` instead. */
  export const outboundSchema = V3UnifyStatusRequestResponse$outboundSchema;
  /** @deprecated use `V3UnifyStatusRequestResponse$Outbound` instead. */
  export type Outbound = V3UnifyStatusRequestResponse$Outbound;
}

export function v3UnifyStatusRequestResponseToJSON(
  v3UnifyStatusRequestResponse: V3UnifyStatusRequestResponse,
): string {
  return JSON.stringify(
    V3UnifyStatusRequestResponse$outboundSchema.parse(
      v3UnifyStatusRequestResponse,
    ),
  );
}

export function v3UnifyStatusRequestResponseFromJSON(
  jsonString: string,
): SafeParseResult<V3UnifyStatusRequestResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3UnifyStatusRequestResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3UnifyStatusRequestResponse' from JSON`,
  );
}
