/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V3VerifyBatchRequestResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Successful request.
   */
  v3VerifyBatchResponse?: components.V3VerifyBatchResponse | undefined;
};

/** @internal */
export const V3VerifyBatchRequestResponse$inboundSchema: z.ZodType<
  V3VerifyBatchRequestResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  V3VerifyBatchResponse: components.V3VerifyBatchResponse$inboundSchema
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "V3VerifyBatchResponse": "v3VerifyBatchResponse",
  });
});

/** @internal */
export type V3VerifyBatchRequestResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  V3VerifyBatchResponse?: components.V3VerifyBatchResponse$Outbound | undefined;
};

/** @internal */
export const V3VerifyBatchRequestResponse$outboundSchema: z.ZodType<
  V3VerifyBatchRequestResponse$Outbound,
  z.ZodTypeDef,
  V3VerifyBatchRequestResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  v3VerifyBatchResponse: components.V3VerifyBatchResponse$outboundSchema
    .optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    v3VerifyBatchResponse: "V3VerifyBatchResponse",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3VerifyBatchRequestResponse$ {
  /** @deprecated use `V3VerifyBatchRequestResponse$inboundSchema` instead. */
  export const inboundSchema = V3VerifyBatchRequestResponse$inboundSchema;
  /** @deprecated use `V3VerifyBatchRequestResponse$outboundSchema` instead. */
  export const outboundSchema = V3VerifyBatchRequestResponse$outboundSchema;
  /** @deprecated use `V3VerifyBatchRequestResponse$Outbound` instead. */
  export type Outbound = V3VerifyBatchRequestResponse$Outbound;
}

export function v3VerifyBatchRequestResponseToJSON(
  v3VerifyBatchRequestResponse: V3VerifyBatchRequestResponse,
): string {
  return JSON.stringify(
    V3VerifyBatchRequestResponse$outboundSchema.parse(
      v3VerifyBatchRequestResponse,
    ),
  );
}

export function v3VerifyBatchRequestResponseFromJSON(
  jsonString: string,
): SafeParseResult<V3VerifyBatchRequestResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3VerifyBatchRequestResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3VerifyBatchRequestResponse' from JSON`,
  );
}
