/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AuthStartRequestSubjectUserAuthenticators,
  AuthStartRequestSubjectUserAuthenticators$inboundSchema,
  AuthStartRequestSubjectUserAuthenticators$Outbound,
  AuthStartRequestSubjectUserAuthenticators$outboundSchema,
} from "./authstartrequestsubjectuserauthenticators.js";
import {
  AuthStartRequestSubjectUserClaim,
  AuthStartRequestSubjectUserClaim$inboundSchema,
  AuthStartRequestSubjectUserClaim$Outbound,
  AuthStartRequestSubjectUserClaim$outboundSchema,
} from "./authstartrequestsubjectuserclaim.js";

export type AuthStartRequestSubjectUser = {
  authenticators?: AuthStartRequestSubjectUserAuthenticators | undefined;
  claim?: AuthStartRequestSubjectUserClaim | undefined;
};

/** @internal */
export const AuthStartRequestSubjectUser$inboundSchema: z.ZodType<
  AuthStartRequestSubjectUser,
  z.ZodTypeDef,
  unknown
> = z.object({
  authenticators: AuthStartRequestSubjectUserAuthenticators$inboundSchema
    .optional(),
  claim: AuthStartRequestSubjectUserClaim$inboundSchema.optional(),
});

/** @internal */
export type AuthStartRequestSubjectUser$Outbound = {
  authenticators?:
    | AuthStartRequestSubjectUserAuthenticators$Outbound
    | undefined;
  claim?: AuthStartRequestSubjectUserClaim$Outbound | undefined;
};

/** @internal */
export const AuthStartRequestSubjectUser$outboundSchema: z.ZodType<
  AuthStartRequestSubjectUser$Outbound,
  z.ZodTypeDef,
  AuthStartRequestSubjectUser
> = z.object({
  authenticators: AuthStartRequestSubjectUserAuthenticators$outboundSchema
    .optional(),
  claim: AuthStartRequestSubjectUserClaim$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AuthStartRequestSubjectUser$ {
  /** @deprecated use `AuthStartRequestSubjectUser$inboundSchema` instead. */
  export const inboundSchema = AuthStartRequestSubjectUser$inboundSchema;
  /** @deprecated use `AuthStartRequestSubjectUser$outboundSchema` instead. */
  export const outboundSchema = AuthStartRequestSubjectUser$outboundSchema;
  /** @deprecated use `AuthStartRequestSubjectUser$Outbound` instead. */
  export type Outbound = AuthStartRequestSubjectUser$Outbound;
}

export function authStartRequestSubjectUserToJSON(
  authStartRequestSubjectUser: AuthStartRequestSubjectUser,
): string {
  return JSON.stringify(
    AuthStartRequestSubjectUser$outboundSchema.parse(
      authStartRequestSubjectUser,
    ),
  );
}

export function authStartRequestSubjectUserFromJSON(
  jsonString: string,
): SafeParseResult<AuthStartRequestSubjectUser, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthStartRequestSubjectUser$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthStartRequestSubjectUser' from JSON`,
  );
}
