/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AuthStartRequestSubjectDeviceAuthenticators,
  AuthStartRequestSubjectDeviceAuthenticators$inboundSchema,
  AuthStartRequestSubjectDeviceAuthenticators$Outbound,
  AuthStartRequestSubjectDeviceAuthenticators$outboundSchema,
} from "./authstartrequestsubjectdeviceauthenticators.js";
import {
  AuthStartRequestSubjectDeviceClaim,
  AuthStartRequestSubjectDeviceClaim$inboundSchema,
  AuthStartRequestSubjectDeviceClaim$Outbound,
  AuthStartRequestSubjectDeviceClaim$outboundSchema,
} from "./authstartrequestsubjectdeviceclaim.js";

export type AuthStartRequestSubjectDevice = {
  authenticators?: AuthStartRequestSubjectDeviceAuthenticators | undefined;
  claim?: AuthStartRequestSubjectDeviceClaim | undefined;
};

/** @internal */
export const AuthStartRequestSubjectDevice$inboundSchema: z.ZodType<
  AuthStartRequestSubjectDevice,
  z.ZodTypeDef,
  unknown
> = z.object({
  authenticators: AuthStartRequestSubjectDeviceAuthenticators$inboundSchema
    .optional(),
  claim: AuthStartRequestSubjectDeviceClaim$inboundSchema.optional(),
});

/** @internal */
export type AuthStartRequestSubjectDevice$Outbound = {
  authenticators?:
    | AuthStartRequestSubjectDeviceAuthenticators$Outbound
    | undefined;
  claim?: AuthStartRequestSubjectDeviceClaim$Outbound | undefined;
};

/** @internal */
export const AuthStartRequestSubjectDevice$outboundSchema: z.ZodType<
  AuthStartRequestSubjectDevice$Outbound,
  z.ZodTypeDef,
  AuthStartRequestSubjectDevice
> = z.object({
  authenticators: AuthStartRequestSubjectDeviceAuthenticators$outboundSchema
    .optional(),
  claim: AuthStartRequestSubjectDeviceClaim$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AuthStartRequestSubjectDevice$ {
  /** @deprecated use `AuthStartRequestSubjectDevice$inboundSchema` instead. */
  export const inboundSchema = AuthStartRequestSubjectDevice$inboundSchema;
  /** @deprecated use `AuthStartRequestSubjectDevice$outboundSchema` instead. */
  export const outboundSchema = AuthStartRequestSubjectDevice$outboundSchema;
  /** @deprecated use `AuthStartRequestSubjectDevice$Outbound` instead. */
  export type Outbound = AuthStartRequestSubjectDevice$Outbound;
}

export function authStartRequestSubjectDeviceToJSON(
  authStartRequestSubjectDevice: AuthStartRequestSubjectDevice,
): string {
  return JSON.stringify(
    AuthStartRequestSubjectDevice$outboundSchema.parse(
      authStartRequestSubjectDevice,
    ),
  );
}

export function authStartRequestSubjectDeviceFromJSON(
  jsonString: string,
): SafeParseResult<AuthStartRequestSubjectDevice, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthStartRequestSubjectDevice$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthStartRequestSubjectDevice' from JSON`,
  );
}
