/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AuthFinishRequest = {
  /**
   * AuthID is the unique ID of the auth flow to retrieve the result.
   */
  authId: string;
};

/** @internal */
export const AuthFinishRequest$inboundSchema: z.ZodType<
  AuthFinishRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  authId: z.string(),
});

/** @internal */
export type AuthFinishRequest$Outbound = {
  authId: string;
};

/** @internal */
export const AuthFinishRequest$outboundSchema: z.ZodType<
  AuthFinishRequest$Outbound,
  z.ZodTypeDef,
  AuthFinishRequest
> = z.object({
  authId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AuthFinishRequest$ {
  /** @deprecated use `AuthFinishRequest$inboundSchema` instead. */
  export const inboundSchema = AuthFinishRequest$inboundSchema;
  /** @deprecated use `AuthFinishRequest$outboundSchema` instead. */
  export const outboundSchema = AuthFinishRequest$outboundSchema;
  /** @deprecated use `AuthFinishRequest$Outbound` instead. */
  export type Outbound = AuthFinishRequest$Outbound;
}

export function authFinishRequestToJSON(
  authFinishRequest: AuthFinishRequest,
): string {
  return JSON.stringify(
    AuthFinishRequest$outboundSchema.parse(authFinishRequest),
  );
}

export function authFinishRequestFromJSON(
  jsonString: string,
): SafeParseResult<AuthFinishRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthFinishRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthFinishRequest' from JSON`,
  );
}
