/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Fingerprint = {};

export type AuthFinishResponseRawSignals = {
  /**
   * Fingerprint includes raw device signals from fingerprint
   */
  fingerprint?: { [k: string]: Fingerprint } | undefined;
};

/** @internal */
export const Fingerprint$inboundSchema: z.ZodType<
  Fingerprint,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type Fingerprint$Outbound = {};

/** @internal */
export const Fingerprint$outboundSchema: z.ZodType<
  Fingerprint$Outbound,
  z.ZodTypeDef,
  Fingerprint
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Fingerprint$ {
  /** @deprecated use `Fingerprint$inboundSchema` instead. */
  export const inboundSchema = Fingerprint$inboundSchema;
  /** @deprecated use `Fingerprint$outboundSchema` instead. */
  export const outboundSchema = Fingerprint$outboundSchema;
  /** @deprecated use `Fingerprint$Outbound` instead. */
  export type Outbound = Fingerprint$Outbound;
}

export function fingerprintToJSON(fingerprint: Fingerprint): string {
  return JSON.stringify(Fingerprint$outboundSchema.parse(fingerprint));
}

export function fingerprintFromJSON(
  jsonString: string,
): SafeParseResult<Fingerprint, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Fingerprint$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Fingerprint' from JSON`,
  );
}

/** @internal */
export const AuthFinishResponseRawSignals$inboundSchema: z.ZodType<
  AuthFinishResponseRawSignals,
  z.ZodTypeDef,
  unknown
> = z.object({
  fingerprint: z.record(z.lazy(() => Fingerprint$inboundSchema)).optional(),
});

/** @internal */
export type AuthFinishResponseRawSignals$Outbound = {
  fingerprint?: { [k: string]: Fingerprint$Outbound } | undefined;
};

/** @internal */
export const AuthFinishResponseRawSignals$outboundSchema: z.ZodType<
  AuthFinishResponseRawSignals$Outbound,
  z.ZodTypeDef,
  AuthFinishResponseRawSignals
> = z.object({
  fingerprint: z.record(z.lazy(() => Fingerprint$outboundSchema)).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AuthFinishResponseRawSignals$ {
  /** @deprecated use `AuthFinishResponseRawSignals$inboundSchema` instead. */
  export const inboundSchema = AuthFinishResponseRawSignals$inboundSchema;
  /** @deprecated use `AuthFinishResponseRawSignals$outboundSchema` instead. */
  export const outboundSchema = AuthFinishResponseRawSignals$outboundSchema;
  /** @deprecated use `AuthFinishResponseRawSignals$Outbound` instead. */
  export type Outbound = AuthFinishResponseRawSignals$Outbound;
}

export function authFinishResponseRawSignalsToJSON(
  authFinishResponseRawSignals: AuthFinishResponseRawSignals,
): string {
  return JSON.stringify(
    AuthFinishResponseRawSignals$outboundSchema.parse(
      authFinishResponseRawSignals,
    ),
  );
}

export function authFinishResponseRawSignalsFromJSON(
  jsonString: string,
): SafeParseResult<AuthFinishResponseRawSignals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthFinishResponseRawSignals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthFinishResponseRawSignals' from JSON`,
  );
}
