/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AuthFinishResponseSubjectCardResultSuccessClaim,
  AuthFinishResponseSubjectCardResultSuccessClaim$inboundSchema,
  AuthFinishResponseSubjectCardResultSuccessClaim$Outbound,
  AuthFinishResponseSubjectCardResultSuccessClaim$outboundSchema,
} from "./authfinishresponsesubjectcardresultsuccessclaim.js";

export type AuthFinishResponseSubjectCardResultSuccess = {
  authenticatorType?: string | undefined;
  claim?: AuthFinishResponseSubjectCardResultSuccessClaim | undefined;
  /**
   * CreatedAt field is in Unix time which is the number of seconds elapsed since January 1, 1970 UTC.
   */
  createdAt?: number | undefined;
};

/** @internal */
export const AuthFinishResponseSubjectCardResultSuccess$inboundSchema:
  z.ZodType<AuthFinishResponseSubjectCardResultSuccess, z.ZodTypeDef, unknown> =
    z.object({
      authenticatorType: z.string().optional(),
      claim: AuthFinishResponseSubjectCardResultSuccessClaim$inboundSchema
        .optional(),
      createdAt: z.number().int().optional(),
    });

/** @internal */
export type AuthFinishResponseSubjectCardResultSuccess$Outbound = {
  authenticatorType?: string | undefined;
  claim?: AuthFinishResponseSubjectCardResultSuccessClaim$Outbound | undefined;
  createdAt?: number | undefined;
};

/** @internal */
export const AuthFinishResponseSubjectCardResultSuccess$outboundSchema:
  z.ZodType<
    AuthFinishResponseSubjectCardResultSuccess$Outbound,
    z.ZodTypeDef,
    AuthFinishResponseSubjectCardResultSuccess
  > = z.object({
    authenticatorType: z.string().optional(),
    claim: AuthFinishResponseSubjectCardResultSuccessClaim$outboundSchema
      .optional(),
    createdAt: z.number().int().optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AuthFinishResponseSubjectCardResultSuccess$ {
  /** @deprecated use `AuthFinishResponseSubjectCardResultSuccess$inboundSchema` instead. */
  export const inboundSchema =
    AuthFinishResponseSubjectCardResultSuccess$inboundSchema;
  /** @deprecated use `AuthFinishResponseSubjectCardResultSuccess$outboundSchema` instead. */
  export const outboundSchema =
    AuthFinishResponseSubjectCardResultSuccess$outboundSchema;
  /** @deprecated use `AuthFinishResponseSubjectCardResultSuccess$Outbound` instead. */
  export type Outbound = AuthFinishResponseSubjectCardResultSuccess$Outbound;
}

export function authFinishResponseSubjectCardResultSuccessToJSON(
  authFinishResponseSubjectCardResultSuccess:
    AuthFinishResponseSubjectCardResultSuccess,
): string {
  return JSON.stringify(
    AuthFinishResponseSubjectCardResultSuccess$outboundSchema.parse(
      authFinishResponseSubjectCardResultSuccess,
    ),
  );
}

export function authFinishResponseSubjectCardResultSuccessFromJSON(
  jsonString: string,
): SafeParseResult<
  AuthFinishResponseSubjectCardResultSuccess,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      AuthFinishResponseSubjectCardResultSuccess$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'AuthFinishResponseSubjectCardResultSuccess' from JSON`,
  );
}
