/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AuthFinishResponsePushDeliveryExtras,
  AuthFinishResponsePushDeliveryExtras$inboundSchema,
  AuthFinishResponsePushDeliveryExtras$Outbound,
  AuthFinishResponsePushDeliveryExtras$outboundSchema,
} from "./authfinishresponsepushdeliveryextras.js";

export type AuthFinishResponsePushDelivery = {
  extras?: AuthFinishResponsePushDeliveryExtras | undefined;
  response?: string | undefined;
};

/** @internal */
export const AuthFinishResponsePushDelivery$inboundSchema: z.ZodType<
  AuthFinishResponsePushDelivery,
  z.ZodTypeDef,
  unknown
> = z.object({
  extras: AuthFinishResponsePushDeliveryExtras$inboundSchema.optional(),
  response: z.string().optional(),
});

/** @internal */
export type AuthFinishResponsePushDelivery$Outbound = {
  extras?: AuthFinishResponsePushDeliveryExtras$Outbound | undefined;
  response?: string | undefined;
};

/** @internal */
export const AuthFinishResponsePushDelivery$outboundSchema: z.ZodType<
  AuthFinishResponsePushDelivery$Outbound,
  z.ZodTypeDef,
  AuthFinishResponsePushDelivery
> = z.object({
  extras: AuthFinishResponsePushDeliveryExtras$outboundSchema.optional(),
  response: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AuthFinishResponsePushDelivery$ {
  /** @deprecated use `AuthFinishResponsePushDelivery$inboundSchema` instead. */
  export const inboundSchema = AuthFinishResponsePushDelivery$inboundSchema;
  /** @deprecated use `AuthFinishResponsePushDelivery$outboundSchema` instead. */
  export const outboundSchema = AuthFinishResponsePushDelivery$outboundSchema;
  /** @deprecated use `AuthFinishResponsePushDelivery$Outbound` instead. */
  export type Outbound = AuthFinishResponsePushDelivery$Outbound;
}

export function authFinishResponsePushDeliveryToJSON(
  authFinishResponsePushDelivery: AuthFinishResponsePushDelivery,
): string {
  return JSON.stringify(
    AuthFinishResponsePushDelivery$outboundSchema.parse(
      authFinishResponsePushDelivery,
    ),
  );
}

export function authFinishResponsePushDeliveryFromJSON(
  jsonString: string,
): SafeParseResult<AuthFinishResponsePushDelivery, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthFinishResponsePushDelivery$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthFinishResponsePushDelivery' from JSON`,
  );
}
