/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AuthFinishResponseCardError,
  AuthFinishResponseCardError$inboundSchema,
  AuthFinishResponseCardError$Outbound,
  AuthFinishResponseCardError$outboundSchema,
} from "./authfinishresponsecarderror.js";
import {
  AuthFinishResponseSubjectCardResultSuccess,
  AuthFinishResponseSubjectCardResultSuccess$inboundSchema,
  AuthFinishResponseSubjectCardResultSuccess$Outbound,
  AuthFinishResponseSubjectCardResultSuccess$outboundSchema,
} from "./authfinishresponsesubjectcardresultsuccess.js";

export type AuthFinishResponseSubjectCardsResult = {
  error?: AuthFinishResponseCardError | undefined;
  success?: AuthFinishResponseSubjectCardResultSuccess | undefined;
};

/** @internal */
export const AuthFinishResponseSubjectCardsResult$inboundSchema: z.ZodType<
  AuthFinishResponseSubjectCardsResult,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: AuthFinishResponseCardError$inboundSchema.optional(),
  success: AuthFinishResponseSubjectCardResultSuccess$inboundSchema.optional(),
});

/** @internal */
export type AuthFinishResponseSubjectCardsResult$Outbound = {
  error?: AuthFinishResponseCardError$Outbound | undefined;
  success?: AuthFinishResponseSubjectCardResultSuccess$Outbound | undefined;
};

/** @internal */
export const AuthFinishResponseSubjectCardsResult$outboundSchema: z.ZodType<
  AuthFinishResponseSubjectCardsResult$Outbound,
  z.ZodTypeDef,
  AuthFinishResponseSubjectCardsResult
> = z.object({
  error: AuthFinishResponseCardError$outboundSchema.optional(),
  success: AuthFinishResponseSubjectCardResultSuccess$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AuthFinishResponseSubjectCardsResult$ {
  /** @deprecated use `AuthFinishResponseSubjectCardsResult$inboundSchema` instead. */
  export const inboundSchema =
    AuthFinishResponseSubjectCardsResult$inboundSchema;
  /** @deprecated use `AuthFinishResponseSubjectCardsResult$outboundSchema` instead. */
  export const outboundSchema =
    AuthFinishResponseSubjectCardsResult$outboundSchema;
  /** @deprecated use `AuthFinishResponseSubjectCardsResult$Outbound` instead. */
  export type Outbound = AuthFinishResponseSubjectCardsResult$Outbound;
}

export function authFinishResponseSubjectCardsResultToJSON(
  authFinishResponseSubjectCardsResult: AuthFinishResponseSubjectCardsResult,
): string {
  return JSON.stringify(
    AuthFinishResponseSubjectCardsResult$outboundSchema.parse(
      authFinishResponseSubjectCardsResult,
    ),
  );
}

export function authFinishResponseSubjectCardsResultFromJSON(
  jsonString: string,
): SafeParseResult<AuthFinishResponseSubjectCardsResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      AuthFinishResponseSubjectCardsResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthFinishResponseSubjectCardsResult' from JSON`,
  );
}
