/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AuthContinueResponseSubjectsResults,
  AuthContinueResponseSubjectsResults$inboundSchema,
  AuthContinueResponseSubjectsResults$Outbound,
  AuthContinueResponseSubjectsResults$outboundSchema,
} from "./authcontinueresponsesubjectsresults.js";

export type AuthContinueResponse = {
  subjects: AuthContinueResponseSubjectsResults;
};

/** @internal */
export const AuthContinueResponse$inboundSchema: z.ZodType<
  AuthContinueResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  subjects: AuthContinueResponseSubjectsResults$inboundSchema,
});

/** @internal */
export type AuthContinueResponse$Outbound = {
  subjects: AuthContinueResponseSubjectsResults$Outbound;
};

/** @internal */
export const AuthContinueResponse$outboundSchema: z.ZodType<
  AuthContinueResponse$Outbound,
  z.ZodTypeDef,
  AuthContinueResponse
> = z.object({
  subjects: AuthContinueResponseSubjectsResults$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AuthContinueResponse$ {
  /** @deprecated use `AuthContinueResponse$inboundSchema` instead. */
  export const inboundSchema = AuthContinueResponse$inboundSchema;
  /** @deprecated use `AuthContinueResponse$outboundSchema` instead. */
  export const outboundSchema = AuthContinueResponse$outboundSchema;
  /** @deprecated use `AuthContinueResponse$Outbound` instead. */
  export type Outbound = AuthContinueResponse$Outbound;
}

export function authContinueResponseToJSON(
  authContinueResponse: AuthContinueResponse,
): string {
  return JSON.stringify(
    AuthContinueResponse$outboundSchema.parse(authContinueResponse),
  );
}

export function authContinueResponseFromJSON(
  jsonString: string,
): SafeParseResult<AuthContinueResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthContinueResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthContinueResponse' from JSON`,
  );
}
