/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AuthFinishResponseSubjectCardsResult,
  AuthFinishResponseSubjectCardsResult$inboundSchema,
  AuthFinishResponseSubjectCardsResult$Outbound,
  AuthFinishResponseSubjectCardsResult$outboundSchema,
} from "./authfinishresponsesubjectcardsresult.js";
import {
  AuthFinishResponseSubjectDeviceResult,
  AuthFinishResponseSubjectDeviceResult$inboundSchema,
  AuthFinishResponseSubjectDeviceResult$Outbound,
  AuthFinishResponseSubjectDeviceResult$outboundSchema,
} from "./authfinishresponsesubjectdeviceresult.js";
import {
  AuthFinishResponseSubjectMobileResult,
  AuthFinishResponseSubjectMobileResult$inboundSchema,
  AuthFinishResponseSubjectMobileResult$Outbound,
  AuthFinishResponseSubjectMobileResult$outboundSchema,
} from "./authfinishresponsesubjectmobileresult.js";
import {
  AuthFinishResponseSubjectUserResult,
  AuthFinishResponseSubjectUserResult$inboundSchema,
  AuthFinishResponseSubjectUserResult$Outbound,
  AuthFinishResponseSubjectUserResult$outboundSchema,
} from "./authfinishresponsesubjectuserresult.js";

export type AuthFinishResponseSubjects = {
  card?: AuthFinishResponseSubjectCardsResult | undefined;
  device?: AuthFinishResponseSubjectDeviceResult | undefined;
  mobile?: AuthFinishResponseSubjectMobileResult | undefined;
  user?: AuthFinishResponseSubjectUserResult | undefined;
};

/** @internal */
export const AuthFinishResponseSubjects$inboundSchema: z.ZodType<
  AuthFinishResponseSubjects,
  z.ZodTypeDef,
  unknown
> = z.object({
  card: AuthFinishResponseSubjectCardsResult$inboundSchema.optional(),
  device: AuthFinishResponseSubjectDeviceResult$inboundSchema.optional(),
  mobile: AuthFinishResponseSubjectMobileResult$inboundSchema.optional(),
  user: AuthFinishResponseSubjectUserResult$inboundSchema.optional(),
});

/** @internal */
export type AuthFinishResponseSubjects$Outbound = {
  card?: AuthFinishResponseSubjectCardsResult$Outbound | undefined;
  device?: AuthFinishResponseSubjectDeviceResult$Outbound | undefined;
  mobile?: AuthFinishResponseSubjectMobileResult$Outbound | undefined;
  user?: AuthFinishResponseSubjectUserResult$Outbound | undefined;
};

/** @internal */
export const AuthFinishResponseSubjects$outboundSchema: z.ZodType<
  AuthFinishResponseSubjects$Outbound,
  z.ZodTypeDef,
  AuthFinishResponseSubjects
> = z.object({
  card: AuthFinishResponseSubjectCardsResult$outboundSchema.optional(),
  device: AuthFinishResponseSubjectDeviceResult$outboundSchema.optional(),
  mobile: AuthFinishResponseSubjectMobileResult$outboundSchema.optional(),
  user: AuthFinishResponseSubjectUserResult$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AuthFinishResponseSubjects$ {
  /** @deprecated use `AuthFinishResponseSubjects$inboundSchema` instead. */
  export const inboundSchema = AuthFinishResponseSubjects$inboundSchema;
  /** @deprecated use `AuthFinishResponseSubjects$outboundSchema` instead. */
  export const outboundSchema = AuthFinishResponseSubjects$outboundSchema;
  /** @deprecated use `AuthFinishResponseSubjects$Outbound` instead. */
  export type Outbound = AuthFinishResponseSubjects$Outbound;
}

export function authFinishResponseSubjectsToJSON(
  authFinishResponseSubjects: AuthFinishResponseSubjects,
): string {
  return JSON.stringify(
    AuthFinishResponseSubjects$outboundSchema.parse(authFinishResponseSubjects),
  );
}

export function authFinishResponseSubjectsFromJSON(
  jsonString: string,
): SafeParseResult<AuthFinishResponseSubjects, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthFinishResponseSubjects$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthFinishResponseSubjects' from JSON`,
  );
}
