/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AuthContinueResponseSubjectCardResult,
  AuthContinueResponseSubjectCardResult$inboundSchema,
  AuthContinueResponseSubjectCardResult$Outbound,
  AuthContinueResponseSubjectCardResult$outboundSchema,
} from "./authcontinueresponsesubjectcardresult.js";
import {
  AuthContinueResponseSubjectMobileResult,
  AuthContinueResponseSubjectMobileResult$inboundSchema,
  AuthContinueResponseSubjectMobileResult$Outbound,
  AuthContinueResponseSubjectMobileResult$outboundSchema,
} from "./authcontinueresponsesubjectmobileresult.js";

export type AuthContinueResponseSubjectsResults = {
  card?: AuthContinueResponseSubjectCardResult | undefined;
  mobile?: AuthContinueResponseSubjectMobileResult | undefined;
};

/** @internal */
export const AuthContinueResponseSubjectsResults$inboundSchema: z.ZodType<
  AuthContinueResponseSubjectsResults,
  z.ZodTypeDef,
  unknown
> = z.object({
  card: AuthContinueResponseSubjectCardResult$inboundSchema.optional(),
  mobile: AuthContinueResponseSubjectMobileResult$inboundSchema.optional(),
});

/** @internal */
export type AuthContinueResponseSubjectsResults$Outbound = {
  card?: AuthContinueResponseSubjectCardResult$Outbound | undefined;
  mobile?: AuthContinueResponseSubjectMobileResult$Outbound | undefined;
};

/** @internal */
export const AuthContinueResponseSubjectsResults$outboundSchema: z.ZodType<
  AuthContinueResponseSubjectsResults$Outbound,
  z.ZodTypeDef,
  AuthContinueResponseSubjectsResults
> = z.object({
  card: AuthContinueResponseSubjectCardResult$outboundSchema.optional(),
  mobile: AuthContinueResponseSubjectMobileResult$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AuthContinueResponseSubjectsResults$ {
  /** @deprecated use `AuthContinueResponseSubjectsResults$inboundSchema` instead. */
  export const inboundSchema =
    AuthContinueResponseSubjectsResults$inboundSchema;
  /** @deprecated use `AuthContinueResponseSubjectsResults$outboundSchema` instead. */
  export const outboundSchema =
    AuthContinueResponseSubjectsResults$outboundSchema;
  /** @deprecated use `AuthContinueResponseSubjectsResults$Outbound` instead. */
  export type Outbound = AuthContinueResponseSubjectsResults$Outbound;
}

export function authContinueResponseSubjectsResultsToJSON(
  authContinueResponseSubjectsResults: AuthContinueResponseSubjectsResults,
): string {
  return JSON.stringify(
    AuthContinueResponseSubjectsResults$outboundSchema.parse(
      authContinueResponseSubjectsResults,
    ),
  );
}

export function authContinueResponseSubjectsResultsFromJSON(
  jsonString: string,
): SafeParseResult<AuthContinueResponseSubjectsResults, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      AuthContinueResponseSubjectsResults$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthContinueResponseSubjectsResults' from JSON`,
  );
}
