/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AuthFinishResponseSubjectMobileResultSuccessClaim = {
  /**
   * MobileNumber bound to the device. Mobile number may be prefixed with a plus sign, but does not need to be for
   *
   * @remarks
   * US. A plus sign is required for international.
   */
  mobileNumber: string;
};

/** @internal */
export const AuthFinishResponseSubjectMobileResultSuccessClaim$inboundSchema:
  z.ZodType<
    AuthFinishResponseSubjectMobileResultSuccessClaim,
    z.ZodTypeDef,
    unknown
  > = z.object({
    mobileNumber: z.string(),
  });

/** @internal */
export type AuthFinishResponseSubjectMobileResultSuccessClaim$Outbound = {
  mobileNumber: string;
};

/** @internal */
export const AuthFinishResponseSubjectMobileResultSuccessClaim$outboundSchema:
  z.ZodType<
    AuthFinishResponseSubjectMobileResultSuccessClaim$Outbound,
    z.ZodTypeDef,
    AuthFinishResponseSubjectMobileResultSuccessClaim
  > = z.object({
    mobileNumber: z.string(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AuthFinishResponseSubjectMobileResultSuccessClaim$ {
  /** @deprecated use `AuthFinishResponseSubjectMobileResultSuccessClaim$inboundSchema` instead. */
  export const inboundSchema =
    AuthFinishResponseSubjectMobileResultSuccessClaim$inboundSchema;
  /** @deprecated use `AuthFinishResponseSubjectMobileResultSuccessClaim$outboundSchema` instead. */
  export const outboundSchema =
    AuthFinishResponseSubjectMobileResultSuccessClaim$outboundSchema;
  /** @deprecated use `AuthFinishResponseSubjectMobileResultSuccessClaim$Outbound` instead. */
  export type Outbound =
    AuthFinishResponseSubjectMobileResultSuccessClaim$Outbound;
}

export function authFinishResponseSubjectMobileResultSuccessClaimToJSON(
  authFinishResponseSubjectMobileResultSuccessClaim:
    AuthFinishResponseSubjectMobileResultSuccessClaim,
): string {
  return JSON.stringify(
    AuthFinishResponseSubjectMobileResultSuccessClaim$outboundSchema.parse(
      authFinishResponseSubjectMobileResultSuccessClaim,
    ),
  );
}

export function authFinishResponseSubjectMobileResultSuccessClaimFromJSON(
  jsonString: string,
): SafeParseResult<
  AuthFinishResponseSubjectMobileResultSuccessClaim,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      AuthFinishResponseSubjectMobileResultSuccessClaim$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'AuthFinishResponseSubjectMobileResultSuccessClaim' from JSON`,
  );
}
