/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AuthFinishResponseRawSignals,
  AuthFinishResponseRawSignals$inboundSchema,
  AuthFinishResponseRawSignals$Outbound,
  AuthFinishResponseRawSignals$outboundSchema,
} from "./authfinishresponserawsignals.js";
import {
  SubjectDeviceResultSuccessExtrasTrust,
  SubjectDeviceResultSuccessExtrasTrust$inboundSchema,
  SubjectDeviceResultSuccessExtrasTrust$Outbound,
  SubjectDeviceResultSuccessExtrasTrust$outboundSchema,
} from "./subjectdeviceresultsuccessextrastrust.js";

export type AuthFinishResponseSubjectDeviceResultSuccessExtras = {
  /**
   * DeviceCapabilities contains the available device capabilities (webauthn, face, fingerprint).
   */
  deviceCapabilities?: Array<string> | undefined;
  /**
   * DeviceAuthType contains description of the type of client device used for auth: 'web' or 'mobile'.
   */
  deviceType?: string | undefined;
  /**
   * KeyType indicates the type of the key used for the authentication. This parameter is only included with UPK transactions.
   */
  keyType?: string | undefined;
  rawSignals?: AuthFinishResponseRawSignals | undefined;
  /**
   * SupportedUvLevel indicates the level of user verification supported on the device.
   */
  supportedUvLevel?: Array<number> | undefined;
  trust?: SubjectDeviceResultSuccessExtrasTrust | undefined;
};

/** @internal */
export const AuthFinishResponseSubjectDeviceResultSuccessExtras$inboundSchema:
  z.ZodType<
    AuthFinishResponseSubjectDeviceResultSuccessExtras,
    z.ZodTypeDef,
    unknown
  > = z.object({
    deviceCapabilities: z.array(z.string()).optional(),
    deviceType: z.string().optional(),
    keyType: z.string().optional(),
    rawSignals: AuthFinishResponseRawSignals$inboundSchema.optional(),
    supportedUvLevel: z.array(z.number().int()).optional(),
    trust: SubjectDeviceResultSuccessExtrasTrust$inboundSchema.optional(),
  });

/** @internal */
export type AuthFinishResponseSubjectDeviceResultSuccessExtras$Outbound = {
  deviceCapabilities?: Array<string> | undefined;
  deviceType?: string | undefined;
  keyType?: string | undefined;
  rawSignals?: AuthFinishResponseRawSignals$Outbound | undefined;
  supportedUvLevel?: Array<number> | undefined;
  trust?: SubjectDeviceResultSuccessExtrasTrust$Outbound | undefined;
};

/** @internal */
export const AuthFinishResponseSubjectDeviceResultSuccessExtras$outboundSchema:
  z.ZodType<
    AuthFinishResponseSubjectDeviceResultSuccessExtras$Outbound,
    z.ZodTypeDef,
    AuthFinishResponseSubjectDeviceResultSuccessExtras
  > = z.object({
    deviceCapabilities: z.array(z.string()).optional(),
    deviceType: z.string().optional(),
    keyType: z.string().optional(),
    rawSignals: AuthFinishResponseRawSignals$outboundSchema.optional(),
    supportedUvLevel: z.array(z.number().int()).optional(),
    trust: SubjectDeviceResultSuccessExtrasTrust$outboundSchema.optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AuthFinishResponseSubjectDeviceResultSuccessExtras$ {
  /** @deprecated use `AuthFinishResponseSubjectDeviceResultSuccessExtras$inboundSchema` instead. */
  export const inboundSchema =
    AuthFinishResponseSubjectDeviceResultSuccessExtras$inboundSchema;
  /** @deprecated use `AuthFinishResponseSubjectDeviceResultSuccessExtras$outboundSchema` instead. */
  export const outboundSchema =
    AuthFinishResponseSubjectDeviceResultSuccessExtras$outboundSchema;
  /** @deprecated use `AuthFinishResponseSubjectDeviceResultSuccessExtras$Outbound` instead. */
  export type Outbound =
    AuthFinishResponseSubjectDeviceResultSuccessExtras$Outbound;
}

export function authFinishResponseSubjectDeviceResultSuccessExtrasToJSON(
  authFinishResponseSubjectDeviceResultSuccessExtras:
    AuthFinishResponseSubjectDeviceResultSuccessExtras,
): string {
  return JSON.stringify(
    AuthFinishResponseSubjectDeviceResultSuccessExtras$outboundSchema.parse(
      authFinishResponseSubjectDeviceResultSuccessExtras,
    ),
  );
}

export function authFinishResponseSubjectDeviceResultSuccessExtrasFromJSON(
  jsonString: string,
): SafeParseResult<
  AuthFinishResponseSubjectDeviceResultSuccessExtras,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      AuthFinishResponseSubjectDeviceResultSuccessExtras$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'AuthFinishResponseSubjectDeviceResultSuccessExtras' from JSON`,
  );
}
