/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AuthFinishResponseSubjectMobileResultSuccessClaim,
  AuthFinishResponseSubjectMobileResultSuccessClaim$inboundSchema,
  AuthFinishResponseSubjectMobileResultSuccessClaim$Outbound,
  AuthFinishResponseSubjectMobileResultSuccessClaim$outboundSchema,
} from "./authfinishresponsesubjectmobileresultsuccessclaim.js";
import {
  AuthFinishResponseSubjectMobileResultSuccessExtras,
  AuthFinishResponseSubjectMobileResultSuccessExtras$inboundSchema,
  AuthFinishResponseSubjectMobileResultSuccessExtras$Outbound,
  AuthFinishResponseSubjectMobileResultSuccessExtras$outboundSchema,
} from "./authfinishresponsesubjectmobileresultsuccessextras.js";

export type AuthFinishResponseSubjectMobileResultSuccess = {
  /**
   * AuthenticatorType specifies the type of authenticator used in the auth flow. Values: instant, passive, and
   *
   * @remarks
   * provided.
   */
  authenticatorType: string;
  claim?: AuthFinishResponseSubjectMobileResultSuccessClaim | undefined;
  /**
   * CreatedAt field is in Unix time which is the number of seconds elapsed since January 1, 1970 UTC.
   */
  createdAt?: number | undefined;
  extras?: AuthFinishResponseSubjectMobileResultSuccessExtras | undefined;
};

/** @internal */
export const AuthFinishResponseSubjectMobileResultSuccess$inboundSchema:
  z.ZodType<
    AuthFinishResponseSubjectMobileResultSuccess,
    z.ZodTypeDef,
    unknown
  > = z.object({
    authenticatorType: z.string(),
    claim: AuthFinishResponseSubjectMobileResultSuccessClaim$inboundSchema
      .optional(),
    createdAt: z.number().int().optional(),
    extras: AuthFinishResponseSubjectMobileResultSuccessExtras$inboundSchema
      .optional(),
  });

/** @internal */
export type AuthFinishResponseSubjectMobileResultSuccess$Outbound = {
  authenticatorType: string;
  claim?:
    | AuthFinishResponseSubjectMobileResultSuccessClaim$Outbound
    | undefined;
  createdAt?: number | undefined;
  extras?:
    | AuthFinishResponseSubjectMobileResultSuccessExtras$Outbound
    | undefined;
};

/** @internal */
export const AuthFinishResponseSubjectMobileResultSuccess$outboundSchema:
  z.ZodType<
    AuthFinishResponseSubjectMobileResultSuccess$Outbound,
    z.ZodTypeDef,
    AuthFinishResponseSubjectMobileResultSuccess
  > = z.object({
    authenticatorType: z.string(),
    claim: AuthFinishResponseSubjectMobileResultSuccessClaim$outboundSchema
      .optional(),
    createdAt: z.number().int().optional(),
    extras: AuthFinishResponseSubjectMobileResultSuccessExtras$outboundSchema
      .optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AuthFinishResponseSubjectMobileResultSuccess$ {
  /** @deprecated use `AuthFinishResponseSubjectMobileResultSuccess$inboundSchema` instead. */
  export const inboundSchema =
    AuthFinishResponseSubjectMobileResultSuccess$inboundSchema;
  /** @deprecated use `AuthFinishResponseSubjectMobileResultSuccess$outboundSchema` instead. */
  export const outboundSchema =
    AuthFinishResponseSubjectMobileResultSuccess$outboundSchema;
  /** @deprecated use `AuthFinishResponseSubjectMobileResultSuccess$Outbound` instead. */
  export type Outbound = AuthFinishResponseSubjectMobileResultSuccess$Outbound;
}

export function authFinishResponseSubjectMobileResultSuccessToJSON(
  authFinishResponseSubjectMobileResultSuccess:
    AuthFinishResponseSubjectMobileResultSuccess,
): string {
  return JSON.stringify(
    AuthFinishResponseSubjectMobileResultSuccess$outboundSchema.parse(
      authFinishResponseSubjectMobileResultSuccess,
    ),
  );
}

export function authFinishResponseSubjectMobileResultSuccessFromJSON(
  jsonString: string,
): SafeParseResult<
  AuthFinishResponseSubjectMobileResultSuccess,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      AuthFinishResponseSubjectMobileResultSuccess$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'AuthFinishResponseSubjectMobileResultSuccess' from JSON`,
  );
}
