/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AuthStartRequestSubjectCard,
  AuthStartRequestSubjectCard$inboundSchema,
  AuthStartRequestSubjectCard$Outbound,
  AuthStartRequestSubjectCard$outboundSchema,
} from "./authstartrequestsubjectcard.js";
import {
  AuthStartRequestSubjectDevice,
  AuthStartRequestSubjectDevice$inboundSchema,
  AuthStartRequestSubjectDevice$Outbound,
  AuthStartRequestSubjectDevice$outboundSchema,
} from "./authstartrequestsubjectdevice.js";
import {
  AuthStartRequestSubjectMobile,
  AuthStartRequestSubjectMobile$inboundSchema,
  AuthStartRequestSubjectMobile$Outbound,
  AuthStartRequestSubjectMobile$outboundSchema,
} from "./authstartrequestsubjectmobile.js";
import {
  AuthStartRequestSubjectUser,
  AuthStartRequestSubjectUser$inboundSchema,
  AuthStartRequestSubjectUser$Outbound,
  AuthStartRequestSubjectUser$outboundSchema,
} from "./authstartrequestsubjectuser.js";

export type AuthStartRequestSubjects = {
  card?: AuthStartRequestSubjectCard | undefined;
  device?: AuthStartRequestSubjectDevice | undefined;
  mobile?: AuthStartRequestSubjectMobile | undefined;
  user?: AuthStartRequestSubjectUser | undefined;
};

/** @internal */
export const AuthStartRequestSubjects$inboundSchema: z.ZodType<
  AuthStartRequestSubjects,
  z.ZodTypeDef,
  unknown
> = z.object({
  card: AuthStartRequestSubjectCard$inboundSchema.optional(),
  device: AuthStartRequestSubjectDevice$inboundSchema.optional(),
  mobile: AuthStartRequestSubjectMobile$inboundSchema.optional(),
  user: AuthStartRequestSubjectUser$inboundSchema.optional(),
});

/** @internal */
export type AuthStartRequestSubjects$Outbound = {
  card?: AuthStartRequestSubjectCard$Outbound | undefined;
  device?: AuthStartRequestSubjectDevice$Outbound | undefined;
  mobile?: AuthStartRequestSubjectMobile$Outbound | undefined;
  user?: AuthStartRequestSubjectUser$Outbound | undefined;
};

/** @internal */
export const AuthStartRequestSubjects$outboundSchema: z.ZodType<
  AuthStartRequestSubjects$Outbound,
  z.ZodTypeDef,
  AuthStartRequestSubjects
> = z.object({
  card: AuthStartRequestSubjectCard$outboundSchema.optional(),
  device: AuthStartRequestSubjectDevice$outboundSchema.optional(),
  mobile: AuthStartRequestSubjectMobile$outboundSchema.optional(),
  user: AuthStartRequestSubjectUser$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AuthStartRequestSubjects$ {
  /** @deprecated use `AuthStartRequestSubjects$inboundSchema` instead. */
  export const inboundSchema = AuthStartRequestSubjects$inboundSchema;
  /** @deprecated use `AuthStartRequestSubjects$outboundSchema` instead. */
  export const outboundSchema = AuthStartRequestSubjects$outboundSchema;
  /** @deprecated use `AuthStartRequestSubjects$Outbound` instead. */
  export type Outbound = AuthStartRequestSubjects$Outbound;
}

export function authStartRequestSubjectsToJSON(
  authStartRequestSubjects: AuthStartRequestSubjects,
): string {
  return JSON.stringify(
    AuthStartRequestSubjects$outboundSchema.parse(authStartRequestSubjects),
  );
}

export function authStartRequestSubjectsFromJSON(
  jsonString: string,
): SafeParseResult<AuthStartRequestSubjects, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthStartRequestSubjects$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthStartRequestSubjects' from JSON`,
  );
}
