/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AuthStartRequestSubjectDeviceClaim = {
  deviceId?: string | undefined;
};

/** @internal */
export const AuthStartRequestSubjectDeviceClaim$inboundSchema: z.ZodType<
  AuthStartRequestSubjectDeviceClaim,
  z.ZodTypeDef,
  unknown
> = z.object({
  deviceId: z.string().optional(),
});

/** @internal */
export type AuthStartRequestSubjectDeviceClaim$Outbound = {
  deviceId?: string | undefined;
};

/** @internal */
export const AuthStartRequestSubjectDeviceClaim$outboundSchema: z.ZodType<
  AuthStartRequestSubjectDeviceClaim$Outbound,
  z.ZodTypeDef,
  AuthStartRequestSubjectDeviceClaim
> = z.object({
  deviceId: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AuthStartRequestSubjectDeviceClaim$ {
  /** @deprecated use `AuthStartRequestSubjectDeviceClaim$inboundSchema` instead. */
  export const inboundSchema = AuthStartRequestSubjectDeviceClaim$inboundSchema;
  /** @deprecated use `AuthStartRequestSubjectDeviceClaim$outboundSchema` instead. */
  export const outboundSchema =
    AuthStartRequestSubjectDeviceClaim$outboundSchema;
  /** @deprecated use `AuthStartRequestSubjectDeviceClaim$Outbound` instead. */
  export type Outbound = AuthStartRequestSubjectDeviceClaim$Outbound;
}

export function authStartRequestSubjectDeviceClaimToJSON(
  authStartRequestSubjectDeviceClaim: AuthStartRequestSubjectDeviceClaim,
): string {
  return JSON.stringify(
    AuthStartRequestSubjectDeviceClaim$outboundSchema.parse(
      authStartRequestSubjectDeviceClaim,
    ),
  );
}

export function authStartRequestSubjectDeviceClaimFromJSON(
  jsonString: string,
): SafeParseResult<AuthStartRequestSubjectDeviceClaim, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      AuthStartRequestSubjectDeviceClaim$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthStartRequestSubjectDeviceClaim' from JSON`,
  );
}
