/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AuthStartRequestSubjectCardAuthenticatorAirKeyClaim = {
  /**
   * Optional comma-separated list of PUIDs associated with the cardholder.
   */
  puids?: Array<string> | undefined;
};

/** @internal */
export const AuthStartRequestSubjectCardAuthenticatorAirKeyClaim$inboundSchema:
  z.ZodType<
    AuthStartRequestSubjectCardAuthenticatorAirKeyClaim,
    z.ZodTypeDef,
    unknown
  > = z.object({
    puids: z.array(z.string()).optional(),
  });

/** @internal */
export type AuthStartRequestSubjectCardAuthenticatorAirKeyClaim$Outbound = {
  puids?: Array<string> | undefined;
};

/** @internal */
export const AuthStartRequestSubjectCardAuthenticatorAirKeyClaim$outboundSchema:
  z.ZodType<
    AuthStartRequestSubjectCardAuthenticatorAirKeyClaim$Outbound,
    z.ZodTypeDef,
    AuthStartRequestSubjectCardAuthenticatorAirKeyClaim
  > = z.object({
    puids: z.array(z.string()).optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AuthStartRequestSubjectCardAuthenticatorAirKeyClaim$ {
  /** @deprecated use `AuthStartRequestSubjectCardAuthenticatorAirKeyClaim$inboundSchema` instead. */
  export const inboundSchema =
    AuthStartRequestSubjectCardAuthenticatorAirKeyClaim$inboundSchema;
  /** @deprecated use `AuthStartRequestSubjectCardAuthenticatorAirKeyClaim$outboundSchema` instead. */
  export const outboundSchema =
    AuthStartRequestSubjectCardAuthenticatorAirKeyClaim$outboundSchema;
  /** @deprecated use `AuthStartRequestSubjectCardAuthenticatorAirKeyClaim$Outbound` instead. */
  export type Outbound =
    AuthStartRequestSubjectCardAuthenticatorAirKeyClaim$Outbound;
}

export function authStartRequestSubjectCardAuthenticatorAirKeyClaimToJSON(
  authStartRequestSubjectCardAuthenticatorAirKeyClaim:
    AuthStartRequestSubjectCardAuthenticatorAirKeyClaim,
): string {
  return JSON.stringify(
    AuthStartRequestSubjectCardAuthenticatorAirKeyClaim$outboundSchema.parse(
      authStartRequestSubjectCardAuthenticatorAirKeyClaim,
    ),
  );
}

export function authStartRequestSubjectCardAuthenticatorAirKeyClaimFromJSON(
  jsonString: string,
): SafeParseResult<
  AuthStartRequestSubjectCardAuthenticatorAirKeyClaim,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      AuthStartRequestSubjectCardAuthenticatorAirKeyClaim$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'AuthStartRequestSubjectCardAuthenticatorAirKeyClaim' from JSON`,
  );
}
