/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AuthFinishResponseSubjectUserResultSuccessClaim,
  AuthFinishResponseSubjectUserResultSuccessClaim$inboundSchema,
  AuthFinishResponseSubjectUserResultSuccessClaim$Outbound,
  AuthFinishResponseSubjectUserResultSuccessClaim$outboundSchema,
} from "./authfinishresponsesubjectuserresultsuccessclaim.js";
import {
  AuthFinishResponseUserExtras,
  AuthFinishResponseUserExtras$inboundSchema,
  AuthFinishResponseUserExtras$Outbound,
  AuthFinishResponseUserExtras$outboundSchema,
} from "./authfinishresponseuserextras.js";

export type AuthFinishResponseSubjectUserResultSuccess = {
  authenticatorType?: string | undefined;
  claim?: AuthFinishResponseSubjectUserResultSuccessClaim | undefined;
  /**
   * CreatedAt field is in Unix time which is the number of seconds elapsed since January 1, 1970 UTC.
   */
  createdAt?: number | undefined;
  extras?: AuthFinishResponseUserExtras | undefined;
};

/** @internal */
export const AuthFinishResponseSubjectUserResultSuccess$inboundSchema:
  z.ZodType<AuthFinishResponseSubjectUserResultSuccess, z.ZodTypeDef, unknown> =
    z.object({
      authenticatorType: z.string().optional(),
      claim: AuthFinishResponseSubjectUserResultSuccessClaim$inboundSchema
        .optional(),
      createdAt: z.number().int().optional(),
      extras: AuthFinishResponseUserExtras$inboundSchema.optional(),
    });

/** @internal */
export type AuthFinishResponseSubjectUserResultSuccess$Outbound = {
  authenticatorType?: string | undefined;
  claim?: AuthFinishResponseSubjectUserResultSuccessClaim$Outbound | undefined;
  createdAt?: number | undefined;
  extras?: AuthFinishResponseUserExtras$Outbound | undefined;
};

/** @internal */
export const AuthFinishResponseSubjectUserResultSuccess$outboundSchema:
  z.ZodType<
    AuthFinishResponseSubjectUserResultSuccess$Outbound,
    z.ZodTypeDef,
    AuthFinishResponseSubjectUserResultSuccess
  > = z.object({
    authenticatorType: z.string().optional(),
    claim: AuthFinishResponseSubjectUserResultSuccessClaim$outboundSchema
      .optional(),
    createdAt: z.number().int().optional(),
    extras: AuthFinishResponseUserExtras$outboundSchema.optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AuthFinishResponseSubjectUserResultSuccess$ {
  /** @deprecated use `AuthFinishResponseSubjectUserResultSuccess$inboundSchema` instead. */
  export const inboundSchema =
    AuthFinishResponseSubjectUserResultSuccess$inboundSchema;
  /** @deprecated use `AuthFinishResponseSubjectUserResultSuccess$outboundSchema` instead. */
  export const outboundSchema =
    AuthFinishResponseSubjectUserResultSuccess$outboundSchema;
  /** @deprecated use `AuthFinishResponseSubjectUserResultSuccess$Outbound` instead. */
  export type Outbound = AuthFinishResponseSubjectUserResultSuccess$Outbound;
}

export function authFinishResponseSubjectUserResultSuccessToJSON(
  authFinishResponseSubjectUserResultSuccess:
    AuthFinishResponseSubjectUserResultSuccess,
): string {
  return JSON.stringify(
    AuthFinishResponseSubjectUserResultSuccess$outboundSchema.parse(
      authFinishResponseSubjectUserResultSuccess,
    ),
  );
}

export function authFinishResponseSubjectUserResultSuccessFromJSON(
  jsonString: string,
): SafeParseResult<
  AuthFinishResponseSubjectUserResultSuccess,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      AuthFinishResponseSubjectUserResultSuccess$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'AuthFinishResponseSubjectUserResultSuccess' from JSON`,
  );
}
