/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AuthContinueRequestSubjectMobileClaim,
  AuthContinueRequestSubjectMobileClaim$inboundSchema,
  AuthContinueRequestSubjectMobileClaim$Outbound,
  AuthContinueRequestSubjectMobileClaim$outboundSchema,
} from "./authcontinuerequestsubjectmobileclaim.js";

export type AuthContinueRequestSubjectMobile = {
  claim?: AuthContinueRequestSubjectMobileClaim | undefined;
};

/** @internal */
export const AuthContinueRequestSubjectMobile$inboundSchema: z.ZodType<
  AuthContinueRequestSubjectMobile,
  z.ZodTypeDef,
  unknown
> = z.object({
  claim: AuthContinueRequestSubjectMobileClaim$inboundSchema.optional(),
});

/** @internal */
export type AuthContinueRequestSubjectMobile$Outbound = {
  claim?: AuthContinueRequestSubjectMobileClaim$Outbound | undefined;
};

/** @internal */
export const AuthContinueRequestSubjectMobile$outboundSchema: z.ZodType<
  AuthContinueRequestSubjectMobile$Outbound,
  z.ZodTypeDef,
  AuthContinueRequestSubjectMobile
> = z.object({
  claim: AuthContinueRequestSubjectMobileClaim$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AuthContinueRequestSubjectMobile$ {
  /** @deprecated use `AuthContinueRequestSubjectMobile$inboundSchema` instead. */
  export const inboundSchema = AuthContinueRequestSubjectMobile$inboundSchema;
  /** @deprecated use `AuthContinueRequestSubjectMobile$outboundSchema` instead. */
  export const outboundSchema = AuthContinueRequestSubjectMobile$outboundSchema;
  /** @deprecated use `AuthContinueRequestSubjectMobile$Outbound` instead. */
  export type Outbound = AuthContinueRequestSubjectMobile$Outbound;
}

export function authContinueRequestSubjectMobileToJSON(
  authContinueRequestSubjectMobile: AuthContinueRequestSubjectMobile,
): string {
  return JSON.stringify(
    AuthContinueRequestSubjectMobile$outboundSchema.parse(
      authContinueRequestSubjectMobile,
    ),
  );
}

export function authContinueRequestSubjectMobileFromJSON(
  jsonString: string,
): SafeParseResult<AuthContinueRequestSubjectMobile, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthContinueRequestSubjectMobile$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthContinueRequestSubjectMobile' from JSON`,
  );
}
