/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AuthFinishResponseError,
  AuthFinishResponseError$inboundSchema,
  AuthFinishResponseError$Outbound,
  AuthFinishResponseError$outboundSchema,
} from "./authfinishresponseerror.js";
import {
  AuthFinishResponseSubjectUserResultSuccess,
  AuthFinishResponseSubjectUserResultSuccess$inboundSchema,
  AuthFinishResponseSubjectUserResultSuccess$Outbound,
  AuthFinishResponseSubjectUserResultSuccess$outboundSchema,
} from "./authfinishresponsesubjectuserresultsuccess.js";

export type AuthFinishResponseSubjectUserResult = {
  error?: AuthFinishResponseError | undefined;
  success?: AuthFinishResponseSubjectUserResultSuccess | undefined;
};

/** @internal */
export const AuthFinishResponseSubjectUserResult$inboundSchema: z.ZodType<
  AuthFinishResponseSubjectUserResult,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: AuthFinishResponseError$inboundSchema.optional(),
  success: AuthFinishResponseSubjectUserResultSuccess$inboundSchema.optional(),
});

/** @internal */
export type AuthFinishResponseSubjectUserResult$Outbound = {
  error?: AuthFinishResponseError$Outbound | undefined;
  success?: AuthFinishResponseSubjectUserResultSuccess$Outbound | undefined;
};

/** @internal */
export const AuthFinishResponseSubjectUserResult$outboundSchema: z.ZodType<
  AuthFinishResponseSubjectUserResult$Outbound,
  z.ZodTypeDef,
  AuthFinishResponseSubjectUserResult
> = z.object({
  error: AuthFinishResponseError$outboundSchema.optional(),
  success: AuthFinishResponseSubjectUserResultSuccess$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AuthFinishResponseSubjectUserResult$ {
  /** @deprecated use `AuthFinishResponseSubjectUserResult$inboundSchema` instead. */
  export const inboundSchema =
    AuthFinishResponseSubjectUserResult$inboundSchema;
  /** @deprecated use `AuthFinishResponseSubjectUserResult$outboundSchema` instead. */
  export const outboundSchema =
    AuthFinishResponseSubjectUserResult$outboundSchema;
  /** @deprecated use `AuthFinishResponseSubjectUserResult$Outbound` instead. */
  export type Outbound = AuthFinishResponseSubjectUserResult$Outbound;
}

export function authFinishResponseSubjectUserResultToJSON(
  authFinishResponseSubjectUserResult: AuthFinishResponseSubjectUserResult,
): string {
  return JSON.stringify(
    AuthFinishResponseSubjectUserResult$outboundSchema.parse(
      authFinishResponseSubjectUserResult,
    ),
  );
}

export function authFinishResponseSubjectUserResultFromJSON(
  jsonString: string,
): SafeParseResult<AuthFinishResponseSubjectUserResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      AuthFinishResponseSubjectUserResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthFinishResponseSubjectUserResult' from JSON`,
  );
}
