/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AuthFinishResponseError,
  AuthFinishResponseError$inboundSchema,
  AuthFinishResponseError$Outbound,
  AuthFinishResponseError$outboundSchema,
} from "./authfinishresponseerror.js";
import {
  AuthFinishResponseSubjectDeviceResultSuccess,
  AuthFinishResponseSubjectDeviceResultSuccess$inboundSchema,
  AuthFinishResponseSubjectDeviceResultSuccess$Outbound,
  AuthFinishResponseSubjectDeviceResultSuccess$outboundSchema,
} from "./authfinishresponsesubjectdeviceresultsuccess.js";

export type AuthFinishResponseSubjectDeviceResult = {
  error?: AuthFinishResponseError | undefined;
  success?: AuthFinishResponseSubjectDeviceResultSuccess | undefined;
};

/** @internal */
export const AuthFinishResponseSubjectDeviceResult$inboundSchema: z.ZodType<
  AuthFinishResponseSubjectDeviceResult,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: AuthFinishResponseError$inboundSchema.optional(),
  success: AuthFinishResponseSubjectDeviceResultSuccess$inboundSchema
    .optional(),
});

/** @internal */
export type AuthFinishResponseSubjectDeviceResult$Outbound = {
  error?: AuthFinishResponseError$Outbound | undefined;
  success?: AuthFinishResponseSubjectDeviceResultSuccess$Outbound | undefined;
};

/** @internal */
export const AuthFinishResponseSubjectDeviceResult$outboundSchema: z.ZodType<
  AuthFinishResponseSubjectDeviceResult$Outbound,
  z.ZodTypeDef,
  AuthFinishResponseSubjectDeviceResult
> = z.object({
  error: AuthFinishResponseError$outboundSchema.optional(),
  success: AuthFinishResponseSubjectDeviceResultSuccess$outboundSchema
    .optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AuthFinishResponseSubjectDeviceResult$ {
  /** @deprecated use `AuthFinishResponseSubjectDeviceResult$inboundSchema` instead. */
  export const inboundSchema =
    AuthFinishResponseSubjectDeviceResult$inboundSchema;
  /** @deprecated use `AuthFinishResponseSubjectDeviceResult$outboundSchema` instead. */
  export const outboundSchema =
    AuthFinishResponseSubjectDeviceResult$outboundSchema;
  /** @deprecated use `AuthFinishResponseSubjectDeviceResult$Outbound` instead. */
  export type Outbound = AuthFinishResponseSubjectDeviceResult$Outbound;
}

export function authFinishResponseSubjectDeviceResultToJSON(
  authFinishResponseSubjectDeviceResult: AuthFinishResponseSubjectDeviceResult,
): string {
  return JSON.stringify(
    AuthFinishResponseSubjectDeviceResult$outboundSchema.parse(
      authFinishResponseSubjectDeviceResult,
    ),
  );
}

export function authFinishResponseSubjectDeviceResultFromJSON(
  jsonString: string,
): SafeParseResult<AuthFinishResponseSubjectDeviceResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      AuthFinishResponseSubjectDeviceResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthFinishResponseSubjectDeviceResult' from JSON`,
  );
}
