/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AuthStartRequestSubjectMobileAuthenticators,
  AuthStartRequestSubjectMobileAuthenticators$inboundSchema,
  AuthStartRequestSubjectMobileAuthenticators$Outbound,
  AuthStartRequestSubjectMobileAuthenticators$outboundSchema,
} from "./authstartrequestsubjectmobileauthenticators.js";
import {
  AuthStartRequestSubjectMobileClaim,
  AuthStartRequestSubjectMobileClaim$inboundSchema,
  AuthStartRequestSubjectMobileClaim$Outbound,
  AuthStartRequestSubjectMobileClaim$outboundSchema,
} from "./authstartrequestsubjectmobileclaim.js";

export type AuthStartRequestSubjectMobile = {
  authenticators?: AuthStartRequestSubjectMobileAuthenticators | undefined;
  claim?: AuthStartRequestSubjectMobileClaim | undefined;
};

/** @internal */
export const AuthStartRequestSubjectMobile$inboundSchema: z.ZodType<
  AuthStartRequestSubjectMobile,
  z.ZodTypeDef,
  unknown
> = z.object({
  authenticators: AuthStartRequestSubjectMobileAuthenticators$inboundSchema
    .optional(),
  claim: AuthStartRequestSubjectMobileClaim$inboundSchema.optional(),
});

/** @internal */
export type AuthStartRequestSubjectMobile$Outbound = {
  authenticators?:
    | AuthStartRequestSubjectMobileAuthenticators$Outbound
    | undefined;
  claim?: AuthStartRequestSubjectMobileClaim$Outbound | undefined;
};

/** @internal */
export const AuthStartRequestSubjectMobile$outboundSchema: z.ZodType<
  AuthStartRequestSubjectMobile$Outbound,
  z.ZodTypeDef,
  AuthStartRequestSubjectMobile
> = z.object({
  authenticators: AuthStartRequestSubjectMobileAuthenticators$outboundSchema
    .optional(),
  claim: AuthStartRequestSubjectMobileClaim$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AuthStartRequestSubjectMobile$ {
  /** @deprecated use `AuthStartRequestSubjectMobile$inboundSchema` instead. */
  export const inboundSchema = AuthStartRequestSubjectMobile$inboundSchema;
  /** @deprecated use `AuthStartRequestSubjectMobile$outboundSchema` instead. */
  export const outboundSchema = AuthStartRequestSubjectMobile$outboundSchema;
  /** @deprecated use `AuthStartRequestSubjectMobile$Outbound` instead. */
  export type Outbound = AuthStartRequestSubjectMobile$Outbound;
}

export function authStartRequestSubjectMobileToJSON(
  authStartRequestSubjectMobile: AuthStartRequestSubjectMobile,
): string {
  return JSON.stringify(
    AuthStartRequestSubjectMobile$outboundSchema.parse(
      authStartRequestSubjectMobile,
    ),
  );
}

export function authStartRequestSubjectMobileFromJSON(
  jsonString: string,
): SafeParseResult<AuthStartRequestSubjectMobile, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthStartRequestSubjectMobile$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthStartRequestSubjectMobile' from JSON`,
  );
}
