/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AuthFinishResponseError,
  AuthFinishResponseError$inboundSchema,
  AuthFinishResponseError$Outbound,
  AuthFinishResponseError$outboundSchema,
} from "./authfinishresponseerror.js";
import {
  AuthFinishResponseSubjectMobileResultSuccess,
  AuthFinishResponseSubjectMobileResultSuccess$inboundSchema,
  AuthFinishResponseSubjectMobileResultSuccess$Outbound,
  AuthFinishResponseSubjectMobileResultSuccess$outboundSchema,
} from "./authfinishresponsesubjectmobileresultsuccess.js";

export type AuthFinishResponseSubjectMobileResult = {
  error?: AuthFinishResponseError | undefined;
  success?: AuthFinishResponseSubjectMobileResultSuccess | undefined;
};

/** @internal */
export const AuthFinishResponseSubjectMobileResult$inboundSchema: z.ZodType<
  AuthFinishResponseSubjectMobileResult,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: AuthFinishResponseError$inboundSchema.optional(),
  success: AuthFinishResponseSubjectMobileResultSuccess$inboundSchema
    .optional(),
});

/** @internal */
export type AuthFinishResponseSubjectMobileResult$Outbound = {
  error?: AuthFinishResponseError$Outbound | undefined;
  success?: AuthFinishResponseSubjectMobileResultSuccess$Outbound | undefined;
};

/** @internal */
export const AuthFinishResponseSubjectMobileResult$outboundSchema: z.ZodType<
  AuthFinishResponseSubjectMobileResult$Outbound,
  z.ZodTypeDef,
  AuthFinishResponseSubjectMobileResult
> = z.object({
  error: AuthFinishResponseError$outboundSchema.optional(),
  success: AuthFinishResponseSubjectMobileResultSuccess$outboundSchema
    .optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AuthFinishResponseSubjectMobileResult$ {
  /** @deprecated use `AuthFinishResponseSubjectMobileResult$inboundSchema` instead. */
  export const inboundSchema =
    AuthFinishResponseSubjectMobileResult$inboundSchema;
  /** @deprecated use `AuthFinishResponseSubjectMobileResult$outboundSchema` instead. */
  export const outboundSchema =
    AuthFinishResponseSubjectMobileResult$outboundSchema;
  /** @deprecated use `AuthFinishResponseSubjectMobileResult$Outbound` instead. */
  export type Outbound = AuthFinishResponseSubjectMobileResult$Outbound;
}

export function authFinishResponseSubjectMobileResultToJSON(
  authFinishResponseSubjectMobileResult: AuthFinishResponseSubjectMobileResult,
): string {
  return JSON.stringify(
    AuthFinishResponseSubjectMobileResult$outboundSchema.parse(
      authFinishResponseSubjectMobileResult,
    ),
  );
}

export function authFinishResponseSubjectMobileResultFromJSON(
  jsonString: string,
): SafeParseResult<AuthFinishResponseSubjectMobileResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      AuthFinishResponseSubjectMobileResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthFinishResponseSubjectMobileResult' from JSON`,
  );
}
