/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AuthFinishResponsePushDeliveryExtras = {
  distanceFromOriginatingIp?: number | undefined;
  originatingIpGeolocation?: string | undefined;
};

/** @internal */
export const AuthFinishResponsePushDeliveryExtras$inboundSchema: z.ZodType<
  AuthFinishResponsePushDeliveryExtras,
  z.ZodTypeDef,
  unknown
> = z.object({
  distanceFromOriginatingIp: z.number().int().optional(),
  originatingIpGeolocation: z.string().optional(),
});

/** @internal */
export type AuthFinishResponsePushDeliveryExtras$Outbound = {
  distanceFromOriginatingIp?: number | undefined;
  originatingIpGeolocation?: string | undefined;
};

/** @internal */
export const AuthFinishResponsePushDeliveryExtras$outboundSchema: z.ZodType<
  AuthFinishResponsePushDeliveryExtras$Outbound,
  z.ZodTypeDef,
  AuthFinishResponsePushDeliveryExtras
> = z.object({
  distanceFromOriginatingIp: z.number().int().optional(),
  originatingIpGeolocation: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AuthFinishResponsePushDeliveryExtras$ {
  /** @deprecated use `AuthFinishResponsePushDeliveryExtras$inboundSchema` instead. */
  export const inboundSchema =
    AuthFinishResponsePushDeliveryExtras$inboundSchema;
  /** @deprecated use `AuthFinishResponsePushDeliveryExtras$outboundSchema` instead. */
  export const outboundSchema =
    AuthFinishResponsePushDeliveryExtras$outboundSchema;
  /** @deprecated use `AuthFinishResponsePushDeliveryExtras$Outbound` instead. */
  export type Outbound = AuthFinishResponsePushDeliveryExtras$Outbound;
}

export function authFinishResponsePushDeliveryExtrasToJSON(
  authFinishResponsePushDeliveryExtras: AuthFinishResponsePushDeliveryExtras,
): string {
  return JSON.stringify(
    AuthFinishResponsePushDeliveryExtras$outboundSchema.parse(
      authFinishResponsePushDeliveryExtras,
    ),
  );
}

export function authFinishResponsePushDeliveryExtrasFromJSON(
  jsonString: string,
): SafeParseResult<AuthFinishResponsePushDeliveryExtras, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      AuthFinishResponsePushDeliveryExtras$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthFinishResponsePushDeliveryExtras' from JSON`,
  );
}
