/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AuthFinishResponseSubjectCardResultSuccessClaim = {
  puid?: string | undefined;
};

/** @internal */
export const AuthFinishResponseSubjectCardResultSuccessClaim$inboundSchema:
  z.ZodType<
    AuthFinishResponseSubjectCardResultSuccessClaim,
    z.ZodTypeDef,
    unknown
  > = z.object({
    puid: z.string().optional(),
  });

/** @internal */
export type AuthFinishResponseSubjectCardResultSuccessClaim$Outbound = {
  puid?: string | undefined;
};

/** @internal */
export const AuthFinishResponseSubjectCardResultSuccessClaim$outboundSchema:
  z.ZodType<
    AuthFinishResponseSubjectCardResultSuccessClaim$Outbound,
    z.ZodTypeDef,
    AuthFinishResponseSubjectCardResultSuccessClaim
  > = z.object({
    puid: z.string().optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AuthFinishResponseSubjectCardResultSuccessClaim$ {
  /** @deprecated use `AuthFinishResponseSubjectCardResultSuccessClaim$inboundSchema` instead. */
  export const inboundSchema =
    AuthFinishResponseSubjectCardResultSuccessClaim$inboundSchema;
  /** @deprecated use `AuthFinishResponseSubjectCardResultSuccessClaim$outboundSchema` instead. */
  export const outboundSchema =
    AuthFinishResponseSubjectCardResultSuccessClaim$outboundSchema;
  /** @deprecated use `AuthFinishResponseSubjectCardResultSuccessClaim$Outbound` instead. */
  export type Outbound =
    AuthFinishResponseSubjectCardResultSuccessClaim$Outbound;
}

export function authFinishResponseSubjectCardResultSuccessClaimToJSON(
  authFinishResponseSubjectCardResultSuccessClaim:
    AuthFinishResponseSubjectCardResultSuccessClaim,
): string {
  return JSON.stringify(
    AuthFinishResponseSubjectCardResultSuccessClaim$outboundSchema.parse(
      authFinishResponseSubjectCardResultSuccessClaim,
    ),
  );
}

export function authFinishResponseSubjectCardResultSuccessClaimFromJSON(
  jsonString: string,
): SafeParseResult<
  AuthFinishResponseSubjectCardResultSuccessClaim,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      AuthFinishResponseSubjectCardResultSuccessClaim$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'AuthFinishResponseSubjectCardResultSuccessClaim' from JSON`,
  );
}
