/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type LinkedTo = {
  acceptedAt?: number | undefined;
  acceptedString?: string | undefined;
  name?: string | undefined;
  pcid?: string | undefined;
};

/** @internal */
export const LinkedTo$inboundSchema: z.ZodType<
  LinkedTo,
  z.ZodTypeDef,
  unknown
> = z.object({
  acceptedAt: z.number().int().optional(),
  acceptedString: z.string().optional(),
  name: z.string().optional(),
  pcid: z.string().optional(),
});

/** @internal */
export type LinkedTo$Outbound = {
  acceptedAt?: number | undefined;
  acceptedString?: string | undefined;
  name?: string | undefined;
  pcid?: string | undefined;
};

/** @internal */
export const LinkedTo$outboundSchema: z.ZodType<
  LinkedTo$Outbound,
  z.ZodTypeDef,
  LinkedTo
> = z.object({
  acceptedAt: z.number().int().optional(),
  acceptedString: z.string().optional(),
  name: z.string().optional(),
  pcid: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LinkedTo$ {
  /** @deprecated use `LinkedTo$inboundSchema` instead. */
  export const inboundSchema = LinkedTo$inboundSchema;
  /** @deprecated use `LinkedTo$outboundSchema` instead. */
  export const outboundSchema = LinkedTo$outboundSchema;
  /** @deprecated use `LinkedTo$Outbound` instead. */
  export type Outbound = LinkedTo$Outbound;
}

export function linkedToToJSON(linkedTo: LinkedTo): string {
  return JSON.stringify(LinkedTo$outboundSchema.parse(linkedTo));
}

export function linkedToFromJSON(
  jsonString: string,
): SafeParseResult<LinkedTo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LinkedTo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LinkedTo' from JSON`,
  );
}
