/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type LinkedAccount = {
  customerName?: string | undefined;
  proveAccountId?: string | undefined;
  proveId?: string | undefined;
};

/** @internal */
export const LinkedAccount$inboundSchema: z.ZodType<
  LinkedAccount,
  z.ZodTypeDef,
  unknown
> = z.object({
  customerName: z.string().optional(),
  proveAccountId: z.string().optional(),
  proveId: z.string().optional(),
});

/** @internal */
export type LinkedAccount$Outbound = {
  customerName?: string | undefined;
  proveAccountId?: string | undefined;
  proveId?: string | undefined;
};

/** @internal */
export const LinkedAccount$outboundSchema: z.ZodType<
  LinkedAccount$Outbound,
  z.ZodTypeDef,
  LinkedAccount
> = z.object({
  customerName: z.string().optional(),
  proveAccountId: z.string().optional(),
  proveId: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LinkedAccount$ {
  /** @deprecated use `LinkedAccount$inboundSchema` instead. */
  export const inboundSchema = LinkedAccount$inboundSchema;
  /** @deprecated use `LinkedAccount$outboundSchema` instead. */
  export const outboundSchema = LinkedAccount$outboundSchema;
  /** @deprecated use `LinkedAccount$Outbound` instead. */
  export type Outbound = LinkedAccount$Outbound;
}

export function linkedAccountToJSON(linkedAccount: LinkedAccount): string {
  return JSON.stringify(LinkedAccount$outboundSchema.parse(linkedAccount));
}

export function linkedAccountFromJSON(
  jsonString: string,
): SafeParseResult<LinkedAccount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LinkedAccount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LinkedAccount' from JSON`,
  );
}
