/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SubjectDeviceResultSuccessExtrasTrust = {
  /**
   * ReasonCodes contains a list of the reason codes detected on the device.
   */
  reasonCodes?: Array<number> | undefined;
};

/** @internal */
export const SubjectDeviceResultSuccessExtrasTrust$inboundSchema: z.ZodType<
  SubjectDeviceResultSuccessExtrasTrust,
  z.ZodTypeDef,
  unknown
> = z.object({
  reasonCodes: z.array(z.number().int()).optional(),
});

/** @internal */
export type SubjectDeviceResultSuccessExtrasTrust$Outbound = {
  reasonCodes?: Array<number> | undefined;
};

/** @internal */
export const SubjectDeviceResultSuccessExtrasTrust$outboundSchema: z.ZodType<
  SubjectDeviceResultSuccessExtrasTrust$Outbound,
  z.ZodTypeDef,
  SubjectDeviceResultSuccessExtrasTrust
> = z.object({
  reasonCodes: z.array(z.number().int()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SubjectDeviceResultSuccessExtrasTrust$ {
  /** @deprecated use `SubjectDeviceResultSuccessExtrasTrust$inboundSchema` instead. */
  export const inboundSchema =
    SubjectDeviceResultSuccessExtrasTrust$inboundSchema;
  /** @deprecated use `SubjectDeviceResultSuccessExtrasTrust$outboundSchema` instead. */
  export const outboundSchema =
    SubjectDeviceResultSuccessExtrasTrust$outboundSchema;
  /** @deprecated use `SubjectDeviceResultSuccessExtrasTrust$Outbound` instead. */
  export type Outbound = SubjectDeviceResultSuccessExtrasTrust$Outbound;
}

export function subjectDeviceResultSuccessExtrasTrustToJSON(
  subjectDeviceResultSuccessExtrasTrust: SubjectDeviceResultSuccessExtrasTrust,
): string {
  return JSON.stringify(
    SubjectDeviceResultSuccessExtrasTrust$outboundSchema.parse(
      subjectDeviceResultSuccessExtrasTrust,
    ),
  );
}

export function subjectDeviceResultSuccessExtrasTrustFromJSON(
  jsonString: string,
): SafeParseResult<SubjectDeviceResultSuccessExtrasTrust, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      SubjectDeviceResultSuccessExtrasTrust$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SubjectDeviceResultSuccessExtrasTrust' from JSON`,
  );
}
