/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Response body for the V3 Activate Identity API.
 */
export type V3ActivateIdentityResponse = {
  /**
   * If true, the activate operation was successful.
   */
  success: boolean;
};

/** @internal */
export const V3ActivateIdentityResponse$inboundSchema: z.ZodType<
  V3ActivateIdentityResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
});

/** @internal */
export type V3ActivateIdentityResponse$Outbound = {
  success: boolean;
};

/** @internal */
export const V3ActivateIdentityResponse$outboundSchema: z.ZodType<
  V3ActivateIdentityResponse$Outbound,
  z.ZodTypeDef,
  V3ActivateIdentityResponse
> = z.object({
  success: z.boolean(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3ActivateIdentityResponse$ {
  /** @deprecated use `V3ActivateIdentityResponse$inboundSchema` instead. */
  export const inboundSchema = V3ActivateIdentityResponse$inboundSchema;
  /** @deprecated use `V3ActivateIdentityResponse$outboundSchema` instead. */
  export const outboundSchema = V3ActivateIdentityResponse$outboundSchema;
  /** @deprecated use `V3ActivateIdentityResponse$Outbound` instead. */
  export type Outbound = V3ActivateIdentityResponse$Outbound;
}

export function v3ActivateIdentityResponseToJSON(
  v3ActivateIdentityResponse: V3ActivateIdentityResponse,
): string {
  return JSON.stringify(
    V3ActivateIdentityResponse$outboundSchema.parse(v3ActivateIdentityResponse),
  );
}

export function v3ActivateIdentityResponseFromJSON(
  jsonString: string,
): SafeParseResult<V3ActivateIdentityResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3ActivateIdentityResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3ActivateIdentityResponse' from JSON`,
  );
}
