/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V3DeviceRevokeResponse = {
  /**
   * Whether the device was successfully revoked.
   */
  success: boolean;
};

/** @internal */
export const V3DeviceRevokeResponse$inboundSchema: z.ZodType<
  V3DeviceRevokeResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
});

/** @internal */
export type V3DeviceRevokeResponse$Outbound = {
  success: boolean;
};

/** @internal */
export const V3DeviceRevokeResponse$outboundSchema: z.ZodType<
  V3DeviceRevokeResponse$Outbound,
  z.ZodTypeDef,
  V3DeviceRevokeResponse
> = z.object({
  success: z.boolean(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3DeviceRevokeResponse$ {
  /** @deprecated use `V3DeviceRevokeResponse$inboundSchema` instead. */
  export const inboundSchema = V3DeviceRevokeResponse$inboundSchema;
  /** @deprecated use `V3DeviceRevokeResponse$outboundSchema` instead. */
  export const outboundSchema = V3DeviceRevokeResponse$outboundSchema;
  /** @deprecated use `V3DeviceRevokeResponse$Outbound` instead. */
  export type Outbound = V3DeviceRevokeResponse$Outbound;
}

export function v3DeviceRevokeResponseToJSON(
  v3DeviceRevokeResponse: V3DeviceRevokeResponse,
): string {
  return JSON.stringify(
    V3DeviceRevokeResponse$outboundSchema.parse(v3DeviceRevokeResponse),
  );
}

export function v3DeviceRevokeResponseFromJSON(
  jsonString: string,
): SafeParseResult<V3DeviceRevokeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3DeviceRevokeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3DeviceRevokeResponse' from JSON`,
  );
}
