/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  Result,
  Result$inboundSchema,
  Result$Outbound,
  Result$outboundSchema,
} from "./result.js";

export type V3DiscoverResponse = {
  /**
   * A list of discovered attributes for the given ProveID.
   */
  results?: Array<Result> | undefined;
};

/** @internal */
export const V3DiscoverResponse$inboundSchema: z.ZodType<
  V3DiscoverResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  results: z.array(Result$inboundSchema).optional(),
});

/** @internal */
export type V3DiscoverResponse$Outbound = {
  results?: Array<Result$Outbound> | undefined;
};

/** @internal */
export const V3DiscoverResponse$outboundSchema: z.ZodType<
  V3DiscoverResponse$Outbound,
  z.ZodTypeDef,
  V3DiscoverResponse
> = z.object({
  results: z.array(Result$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3DiscoverResponse$ {
  /** @deprecated use `V3DiscoverResponse$inboundSchema` instead. */
  export const inboundSchema = V3DiscoverResponse$inboundSchema;
  /** @deprecated use `V3DiscoverResponse$outboundSchema` instead. */
  export const outboundSchema = V3DiscoverResponse$outboundSchema;
  /** @deprecated use `V3DiscoverResponse$Outbound` instead. */
  export type Outbound = V3DiscoverResponse$Outbound;
}

export function v3DiscoverResponseToJSON(
  v3DiscoverResponse: V3DiscoverResponse,
): string {
  return JSON.stringify(
    V3DiscoverResponse$outboundSchema.parse(v3DiscoverResponse),
  );
}

export function v3DiscoverResponseFromJSON(
  jsonString: string,
): SafeParseResult<V3DiscoverResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3DiscoverResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3DiscoverResponse' from JSON`,
  );
}
