/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V3DomainIDResponse = {
  /**
   * Customer friendly name
   */
  name: string;
  /**
   * Customer ID
   */
  pcid: string;
};

/** @internal */
export const V3DomainIDResponse$inboundSchema: z.ZodType<
  V3DomainIDResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  pcid: z.string(),
});

/** @internal */
export type V3DomainIDResponse$Outbound = {
  name: string;
  pcid: string;
};

/** @internal */
export const V3DomainIDResponse$outboundSchema: z.ZodType<
  V3DomainIDResponse$Outbound,
  z.ZodTypeDef,
  V3DomainIDResponse
> = z.object({
  name: z.string(),
  pcid: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3DomainIDResponse$ {
  /** @deprecated use `V3DomainIDResponse$inboundSchema` instead. */
  export const inboundSchema = V3DomainIDResponse$inboundSchema;
  /** @deprecated use `V3DomainIDResponse$outboundSchema` instead. */
  export const outboundSchema = V3DomainIDResponse$outboundSchema;
  /** @deprecated use `V3DomainIDResponse$Outbound` instead. */
  export type Outbound = V3DomainIDResponse$Outbound;
}

export function v3DomainIDResponseToJSON(
  v3DomainIDResponse: V3DomainIDResponse,
): string {
  return JSON.stringify(
    V3DomainIDResponse$outboundSchema.parse(v3DomainIDResponse),
  );
}

export function v3DomainIDResponseFromJSON(
  jsonString: string,
): SafeParseResult<V3DomainIDResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3DomainIDResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3DomainIDResponse' from JSON`,
  );
}
