/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V3DomainConfirmLinkRequest = {
  pcid: string;
};

/** @internal */
export const V3DomainConfirmLinkRequest$inboundSchema: z.ZodType<
  V3DomainConfirmLinkRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  pcid: z.string(),
});

/** @internal */
export type V3DomainConfirmLinkRequest$Outbound = {
  pcid: string;
};

/** @internal */
export const V3DomainConfirmLinkRequest$outboundSchema: z.ZodType<
  V3DomainConfirmLinkRequest$Outbound,
  z.ZodTypeDef,
  V3DomainConfirmLinkRequest
> = z.object({
  pcid: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3DomainConfirmLinkRequest$ {
  /** @deprecated use `V3DomainConfirmLinkRequest$inboundSchema` instead. */
  export const inboundSchema = V3DomainConfirmLinkRequest$inboundSchema;
  /** @deprecated use `V3DomainConfirmLinkRequest$outboundSchema` instead. */
  export const outboundSchema = V3DomainConfirmLinkRequest$outboundSchema;
  /** @deprecated use `V3DomainConfirmLinkRequest$Outbound` instead. */
  export type Outbound = V3DomainConfirmLinkRequest$Outbound;
}

export function v3DomainConfirmLinkRequestToJSON(
  v3DomainConfirmLinkRequest: V3DomainConfirmLinkRequest,
): string {
  return JSON.stringify(
    V3DomainConfirmLinkRequest$outboundSchema.parse(v3DomainConfirmLinkRequest),
  );
}

export function v3DomainConfirmLinkRequestFromJSON(
  jsonString: string,
): SafeParseResult<V3DomainConfirmLinkRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3DomainConfirmLinkRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3DomainConfirmLinkRequest' from JSON`,
  );
}
