/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Request body for the V3 Deactivate Identity API.
 */
export type V3IdentityDeactivateRequest = {
  /**
   * A client-generated unique ID for a specific session. This can be used to identify specific requests. The format of this ID is defined by the client - Prove recommends using a GUID, but any format can be accepted. Do not include Personally Identifiable Information (PII) in this field.
   */
  clientRequestId?: string | undefined;
};

/** @internal */
export const V3IdentityDeactivateRequest$inboundSchema: z.ZodType<
  V3IdentityDeactivateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  clientRequestId: z.string().optional(),
});

/** @internal */
export type V3IdentityDeactivateRequest$Outbound = {
  clientRequestId?: string | undefined;
};

/** @internal */
export const V3IdentityDeactivateRequest$outboundSchema: z.ZodType<
  V3IdentityDeactivateRequest$Outbound,
  z.ZodTypeDef,
  V3IdentityDeactivateRequest
> = z.object({
  clientRequestId: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3IdentityDeactivateRequest$ {
  /** @deprecated use `V3IdentityDeactivateRequest$inboundSchema` instead. */
  export const inboundSchema = V3IdentityDeactivateRequest$inboundSchema;
  /** @deprecated use `V3IdentityDeactivateRequest$outboundSchema` instead. */
  export const outboundSchema = V3IdentityDeactivateRequest$outboundSchema;
  /** @deprecated use `V3IdentityDeactivateRequest$Outbound` instead. */
  export type Outbound = V3IdentityDeactivateRequest$Outbound;
}

export function v3IdentityDeactivateRequestToJSON(
  v3IdentityDeactivateRequest: V3IdentityDeactivateRequest,
): string {
  return JSON.stringify(
    V3IdentityDeactivateRequest$outboundSchema.parse(
      v3IdentityDeactivateRequest,
    ),
  );
}

export function v3IdentityDeactivateRequestFromJSON(
  jsonString: string,
): SafeParseResult<V3IdentityDeactivateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3IdentityDeactivateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3IdentityDeactivateRequest' from JSON`,
  );
}
