/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Response body for the V3 MFA Status API
 */
export type V3MFAStatusResponse = {
  /**
   * Phone number that may have been discovered via Mobile Auth during the process.
   */
  phoneNumber: string;
  success: string;
};

/** @internal */
export const V3MFAStatusResponse$inboundSchema: z.ZodType<
  V3MFAStatusResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  phoneNumber: z.string(),
  success: z.string(),
});

/** @internal */
export type V3MFAStatusResponse$Outbound = {
  phoneNumber: string;
  success: string;
};

/** @internal */
export const V3MFAStatusResponse$outboundSchema: z.ZodType<
  V3MFAStatusResponse$Outbound,
  z.ZodTypeDef,
  V3MFAStatusResponse
> = z.object({
  phoneNumber: z.string(),
  success: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3MFAStatusResponse$ {
  /** @deprecated use `V3MFAStatusResponse$inboundSchema` instead. */
  export const inboundSchema = V3MFAStatusResponse$inboundSchema;
  /** @deprecated use `V3MFAStatusResponse$outboundSchema` instead. */
  export const outboundSchema = V3MFAStatusResponse$outboundSchema;
  /** @deprecated use `V3MFAStatusResponse$Outbound` instead. */
  export type Outbound = V3MFAStatusResponse$Outbound;
}

export function v3MFAStatusResponseToJSON(
  v3MFAStatusResponse: V3MFAStatusResponse,
): string {
  return JSON.stringify(
    V3MFAStatusResponse$outboundSchema.parse(v3MFAStatusResponse),
  );
}

export function v3MFAStatusResponseFromJSON(
  jsonString: string,
): SafeParseResult<V3MFAStatusResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3MFAStatusResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3MFAStatusResponse' from JSON`,
  );
}
