/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The status of the Unify request.
 */
export type Success = {};

export type V3UnifyResponse = {
  /**
   * The one-time use JWT for the client-side SDK.
   */
  authToken?: string | undefined;
  /**
   * The unique ID that Prove generates for the flow. To continue the flow, the field will also be used for each of the subsequent API calls in the same flow - it cannot be reused outside of a single flow.
   */
  correlationId: string;
  /**
   * The status of the Unify request.
   */
  success: Success;
};

/** @internal */
export const Success$inboundSchema: z.ZodType<Success, z.ZodTypeDef, unknown> =
  z.object({});

/** @internal */
export type Success$Outbound = {};

/** @internal */
export const Success$outboundSchema: z.ZodType<
  Success$Outbound,
  z.ZodTypeDef,
  Success
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Success$ {
  /** @deprecated use `Success$inboundSchema` instead. */
  export const inboundSchema = Success$inboundSchema;
  /** @deprecated use `Success$outboundSchema` instead. */
  export const outboundSchema = Success$outboundSchema;
  /** @deprecated use `Success$Outbound` instead. */
  export type Outbound = Success$Outbound;
}

export function successToJSON(success: Success): string {
  return JSON.stringify(Success$outboundSchema.parse(success));
}

export function successFromJSON(
  jsonString: string,
): SafeParseResult<Success, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Success$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Success' from JSON`,
  );
}

/** @internal */
export const V3UnifyResponse$inboundSchema: z.ZodType<
  V3UnifyResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  authToken: z.string().optional(),
  correlationId: z.string(),
  success: z.lazy(() => Success$inboundSchema),
});

/** @internal */
export type V3UnifyResponse$Outbound = {
  authToken?: string | undefined;
  correlationId: string;
  success: Success$Outbound;
};

/** @internal */
export const V3UnifyResponse$outboundSchema: z.ZodType<
  V3UnifyResponse$Outbound,
  z.ZodTypeDef,
  V3UnifyResponse
> = z.object({
  authToken: z.string().optional(),
  correlationId: z.string(),
  success: z.lazy(() => Success$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3UnifyResponse$ {
  /** @deprecated use `V3UnifyResponse$inboundSchema` instead. */
  export const inboundSchema = V3UnifyResponse$inboundSchema;
  /** @deprecated use `V3UnifyResponse$outboundSchema` instead. */
  export const outboundSchema = V3UnifyResponse$outboundSchema;
  /** @deprecated use `V3UnifyResponse$Outbound` instead. */
  export type Outbound = V3UnifyResponse$Outbound;
}

export function v3UnifyResponseToJSON(
  v3UnifyResponse: V3UnifyResponse,
): string {
  return JSON.stringify(V3UnifyResponse$outboundSchema.parse(v3UnifyResponse));
}

export function v3UnifyResponseFromJSON(
  jsonString: string,
): SafeParseResult<V3UnifyResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3UnifyResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3UnifyResponse' from JSON`,
  );
}
