/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V3UnifyStatusResponseEvaluation = {};

export type V3UnifyStatusResponse = {
  /**
   * A client-generated unique ID to identify a specific customer across business lines.
   *
   * @remarks
   * Required if success=true.
   */
  clientHumanId?: string | undefined;
  /**
   * A client-generated unique ID for a specific session. This can be used to identify specific requests.
   *
   * @remarks
   * The format of this ID is defined by the client - Prove recommends using a GUID, but any format can be accepted.
   * Do not include Personally Identifiable Information (PII) in this field.
   */
  clientRequestId?: string | undefined;
  /**
   * The unique identifier for the Prove Key on the device.
   *
   * @remarks
   * Required if success=true.
   */
  deviceId?: string | undefined;
  /**
   * The evaluation result for the policy. This is an upcoming field but is not yet enabled.
   */
  evaluation?: { [k: string]: V3UnifyStatusResponseEvaluation } | undefined;
  /**
   * The number of the mobile phone used during the process.
   *
   * @remarks
   *
   * Required except when MobileAuth is used in US or a valid ProveID is provided.
   */
  phoneNumber?: string | undefined;
  /**
   * A unique ID to identify a specific customer obtained from a successful possession check.
   *
   * @remarks
   * If an existing value is available (e.g. from a previous successful possession check) then it should be returned, otherwise a new value should be generated if success=true.
   * Required if success=true.
   */
  proveId?: string | undefined;
  /**
   * The result of the possession check.
   *
   * @remarks
   * Possible values are `true`, `false`, `pending`, and `possession_required`.
   */
  success: string;
};

/** @internal */
export const V3UnifyStatusResponseEvaluation$inboundSchema: z.ZodType<
  V3UnifyStatusResponseEvaluation,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type V3UnifyStatusResponseEvaluation$Outbound = {};

/** @internal */
export const V3UnifyStatusResponseEvaluation$outboundSchema: z.ZodType<
  V3UnifyStatusResponseEvaluation$Outbound,
  z.ZodTypeDef,
  V3UnifyStatusResponseEvaluation
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3UnifyStatusResponseEvaluation$ {
  /** @deprecated use `V3UnifyStatusResponseEvaluation$inboundSchema` instead. */
  export const inboundSchema = V3UnifyStatusResponseEvaluation$inboundSchema;
  /** @deprecated use `V3UnifyStatusResponseEvaluation$outboundSchema` instead. */
  export const outboundSchema = V3UnifyStatusResponseEvaluation$outboundSchema;
  /** @deprecated use `V3UnifyStatusResponseEvaluation$Outbound` instead. */
  export type Outbound = V3UnifyStatusResponseEvaluation$Outbound;
}

export function v3UnifyStatusResponseEvaluationToJSON(
  v3UnifyStatusResponseEvaluation: V3UnifyStatusResponseEvaluation,
): string {
  return JSON.stringify(
    V3UnifyStatusResponseEvaluation$outboundSchema.parse(
      v3UnifyStatusResponseEvaluation,
    ),
  );
}

export function v3UnifyStatusResponseEvaluationFromJSON(
  jsonString: string,
): SafeParseResult<V3UnifyStatusResponseEvaluation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3UnifyStatusResponseEvaluation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3UnifyStatusResponseEvaluation' from JSON`,
  );
}

/** @internal */
export const V3UnifyStatusResponse$inboundSchema: z.ZodType<
  V3UnifyStatusResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  clientHumanId: z.string().optional(),
  clientRequestId: z.string().optional(),
  deviceId: z.string().optional(),
  evaluation: z.record(
    z.lazy(() => V3UnifyStatusResponseEvaluation$inboundSchema),
  ).optional(),
  phoneNumber: z.string().optional(),
  proveId: z.string().optional(),
  success: z.string(),
});

/** @internal */
export type V3UnifyStatusResponse$Outbound = {
  clientHumanId?: string | undefined;
  clientRequestId?: string | undefined;
  deviceId?: string | undefined;
  evaluation?:
    | { [k: string]: V3UnifyStatusResponseEvaluation$Outbound }
    | undefined;
  phoneNumber?: string | undefined;
  proveId?: string | undefined;
  success: string;
};

/** @internal */
export const V3UnifyStatusResponse$outboundSchema: z.ZodType<
  V3UnifyStatusResponse$Outbound,
  z.ZodTypeDef,
  V3UnifyStatusResponse
> = z.object({
  clientHumanId: z.string().optional(),
  clientRequestId: z.string().optional(),
  deviceId: z.string().optional(),
  evaluation: z.record(
    z.lazy(() => V3UnifyStatusResponseEvaluation$outboundSchema),
  ).optional(),
  phoneNumber: z.string().optional(),
  proveId: z.string().optional(),
  success: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3UnifyStatusResponse$ {
  /** @deprecated use `V3UnifyStatusResponse$inboundSchema` instead. */
  export const inboundSchema = V3UnifyStatusResponse$inboundSchema;
  /** @deprecated use `V3UnifyStatusResponse$outboundSchema` instead. */
  export const outboundSchema = V3UnifyStatusResponse$outboundSchema;
  /** @deprecated use `V3UnifyStatusResponse$Outbound` instead. */
  export type Outbound = V3UnifyStatusResponse$Outbound;
}

export function v3UnifyStatusResponseToJSON(
  v3UnifyStatusResponse: V3UnifyStatusResponse,
): string {
  return JSON.stringify(
    V3UnifyStatusResponse$outboundSchema.parse(v3UnifyStatusResponse),
  );
}

export function v3UnifyStatusResponseFromJSON(
  jsonString: string,
): SafeParseResult<V3UnifyStatusResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3UnifyStatusResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3UnifyStatusResponse' from JSON`,
  );
}
