/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Request body for the V3 Unify API
 */
export type V3UnifyRequest = {
  /**
   * Client Customer ID is a client-generated unique ID for a specific customer.
   */
  clientCustomerId?: string | undefined;
  /**
   * Client Request ID is a client-generated unique ID for a specific session.
   */
  clientRequestId?: string | undefined;
  /**
   * Final target URL is only required when possessionType=desktop. The final target
   *
   * @remarks
   * URL is where the end user will be redirected at the end of Instant Link flow.
   * Acceptable characters are: alphanumeric with symbols '-._+=/:?'.
   */
  finalTargetUrl?: string | undefined;
  /**
   * Phone number is the number of the mobile phone. Optional in US, required in EU.
   *
   * @remarks
   * Not allowed when possessionType is 'none'. Acceptable characters are:
   * alphanumeric with symbols '+'.
   */
  phoneNumber?: string | undefined;
  /**
   * Possession type is based on the method used - either 'desktop' if using desktop,
   *
   * @remarks
   * 'mobile' for iOS/Android native apps and mobile web, or 'none' if no possession
   * check is required. Acceptable options are: 'desktop', 'mobile', and 'none'.
   */
  possessionType: string;
  /**
   * SMSMessage is an optional field to customize the message body sent in the
   *
   * @remarks
   * Instant Link (possessionType=desktop) or OTP (on mobile) SMS message.
   */
  smsMessage?: string | undefined;
};

/** @internal */
export const V3UnifyRequest$inboundSchema: z.ZodType<
  V3UnifyRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  clientCustomerId: z.string().optional(),
  clientRequestId: z.string().optional(),
  finalTargetUrl: z.string().optional(),
  phoneNumber: z.string().optional(),
  possessionType: z.string(),
  smsMessage: z.string().optional(),
});

/** @internal */
export type V3UnifyRequest$Outbound = {
  clientCustomerId?: string | undefined;
  clientRequestId?: string | undefined;
  finalTargetUrl?: string | undefined;
  phoneNumber?: string | undefined;
  possessionType: string;
  smsMessage?: string | undefined;
};

/** @internal */
export const V3UnifyRequest$outboundSchema: z.ZodType<
  V3UnifyRequest$Outbound,
  z.ZodTypeDef,
  V3UnifyRequest
> = z.object({
  clientCustomerId: z.string().optional(),
  clientRequestId: z.string().optional(),
  finalTargetUrl: z.string().optional(),
  phoneNumber: z.string().optional(),
  possessionType: z.string(),
  smsMessage: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3UnifyRequest$ {
  /** @deprecated use `V3UnifyRequest$inboundSchema` instead. */
  export const inboundSchema = V3UnifyRequest$inboundSchema;
  /** @deprecated use `V3UnifyRequest$outboundSchema` instead. */
  export const outboundSchema = V3UnifyRequest$outboundSchema;
  /** @deprecated use `V3UnifyRequest$Outbound` instead. */
  export type Outbound = V3UnifyRequest$Outbound;
}

export function v3UnifyRequestToJSON(v3UnifyRequest: V3UnifyRequest): string {
  return JSON.stringify(V3UnifyRequest$outboundSchema.parse(v3UnifyRequest));
}

export function v3UnifyRequestFromJSON(
  jsonString: string,
): SafeParseResult<V3UnifyRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3UnifyRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3UnifyRequest' from JSON`,
  );
}
