/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V3VerifyRequest = {
  /**
   * A client-generated unique ID for a specific customer. This can be used by clients to link calls related to the same customer, across different requests or sessions.  The format of this ID is defined by the client - Prove recommends using a GUID, but any format can be accepted. Prove does not offer any functionality around the Client Customer ID. Do not include personally identifiable information (PII) in this field.
   */
  clientCustomerId?: string | undefined;
  /**
   * An optional client-generated unique ID our Enterprise customer inputs for that consumer across business lines. If the Enterprise customer has been able to identify a consumer across business lines and has a unique identifier for the consumer, they would input this value to Prove.The format of this ID is defined by the client - Prove recommends using a GUID, but any format can be accepted. Do not include personally identifiable information (PII) in this field.
   */
  clientHumanId?: string | undefined;
  /**
   * A client-generated unique ID for a specific session. This can be used to identify specific requests. The format of this ID is defined by the client - Prove recommends using a GUID, but any format can be accepted. Do not include Personally Identifiable Information (PII) in this field.
   */
  clientRequestId?: string | undefined;
  /**
   * The email address of the customer. Acceptable characters are: alphanumeric with symbols '@.+'.
   */
  emailAddress?: string | undefined;
  /**
   * The first name of the individual. (required IF verificationType=VerifiedUser)
   */
  firstName?: string | undefined;
  /**
   * The IP address of the customer.
   */
  ipAddress?: string | undefined;
  /**
   * The last name of the individual. (required IF verificationType=VerifiedUser)
   */
  lastName?: string | undefined;
  /**
   * The mobile phone number. US phone numbers can be passed in with or without a leading `+1`. International phone numbers require a leading `+1`. Use the appropriate endpoint URL based on the region the number originates from. Acceptable characters are: alphanumeric with symbols '+'.
   */
  phoneNumber: string;
  /**
   * The User agent of the customer.
   */
  userAgent?: string | undefined;
  /**
   * The verification method based on the use case and authorization level.
   */
  verificationType: string;
};

/** @internal */
export const V3VerifyRequest$inboundSchema: z.ZodType<
  V3VerifyRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  clientCustomerId: z.string().optional(),
  clientHumanId: z.string().optional(),
  clientRequestId: z.string().optional(),
  emailAddress: z.string().optional(),
  firstName: z.string().optional(),
  ipAddress: z.string().optional(),
  lastName: z.string().optional(),
  phoneNumber: z.string(),
  userAgent: z.string().optional(),
  verificationType: z.string(),
});

/** @internal */
export type V3VerifyRequest$Outbound = {
  clientCustomerId?: string | undefined;
  clientHumanId?: string | undefined;
  clientRequestId?: string | undefined;
  emailAddress?: string | undefined;
  firstName?: string | undefined;
  ipAddress?: string | undefined;
  lastName?: string | undefined;
  phoneNumber: string;
  userAgent?: string | undefined;
  verificationType: string;
};

/** @internal */
export const V3VerifyRequest$outboundSchema: z.ZodType<
  V3VerifyRequest$Outbound,
  z.ZodTypeDef,
  V3VerifyRequest
> = z.object({
  clientCustomerId: z.string().optional(),
  clientHumanId: z.string().optional(),
  clientRequestId: z.string().optional(),
  emailAddress: z.string().optional(),
  firstName: z.string().optional(),
  ipAddress: z.string().optional(),
  lastName: z.string().optional(),
  phoneNumber: z.string(),
  userAgent: z.string().optional(),
  verificationType: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3VerifyRequest$ {
  /** @deprecated use `V3VerifyRequest$inboundSchema` instead. */
  export const inboundSchema = V3VerifyRequest$inboundSchema;
  /** @deprecated use `V3VerifyRequest$outboundSchema` instead. */
  export const outboundSchema = V3VerifyRequest$outboundSchema;
  /** @deprecated use `V3VerifyRequest$Outbound` instead. */
  export type Outbound = V3VerifyRequest$Outbound;
}

export function v3VerifyRequestToJSON(
  v3VerifyRequest: V3VerifyRequest,
): string {
  return JSON.stringify(V3VerifyRequest$outboundSchema.parse(v3VerifyRequest));
}

export function v3VerifyRequestFromJSON(
  jsonString: string,
): SafeParseResult<V3VerifyRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3VerifyRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3VerifyRequest' from JSON`,
  );
}
